### PR TITLE
Created node-jersey.travis.yml

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Created node-jersey.travis.yml in the PR. Please review

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Comment by nageshlop** [comment]
The repo is not active, last commit was in 2012.

**Comment by gururajrkatti** [comment]
Any updates on this ?

**Comment by kishorkunal-raj** [comment]
As per comment and suggestion by @nageshlop, closing the PR

**Pull request closed without merging**
