### PR TITLE
Added build script for influxdb

### PR DESCRIPTION
**Pull request by bhagat-singh001**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by bhagat-singh001** [comment]
Closing PR for rerun. Travis stuck

**Comment by bhagat-singh001** [comment]
Opening PR for rerun. Travis stuck

**Comment by bhagat-singh001** [comment]
Opening PR for rerun. Travis stuck

**Comment by seth-priya** [comment]
This is now in currency https://github.com/ppc64le/build-scripts/tree/master/i/influxdb

**Pull request closed without merging**
