### PR TITLE
Added castor.travis.yml

### PR DESCRIPTION
**Pull request by sanjaymsh**
Hi,

I have added castor.travis.yml file. The travis log can be tracked here https://travis-ci.com/github/sanjaymsh/castor/builds/213624076. Please review and merge it.

Thanks !!
Sanjay

### CODE REVIEW

**Review by seth-priya — CHANGES_REQUESTED** [review]
why are we removing amd64 support and just running on ppc64le?

**Comment by sanjaymsh** [comment]
> why are we removing amd64 support and just running on ppc64le?

Oraclejdk7&8 was not supported on amd64, but it worked on ppc64. So i removed amd64 and kept ppc64 only for build. I have to raise issue for community of this repo. Please suggest me if there is any other changes required.

Thanks !!

**Comment by sanjaymsh** [comment]
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2020-06-02
Expected feature release number in range of 9 to 17, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

**Comment by sanjaymsh** [comment]
This is the issue coming on travis for oraclejdk8 on AMD64.

> $ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL" Ignoring license option: BCL -- using GPLv2+CE by default install-jdk.sh 2020-06-02 Expected feature release number in range of 9 to 17, but got: 8 The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

Same issue is being observed for oraclejdk7 also for amd64.

**Comment by sanjaymsh** [comment]
An issue #87 has been created on the community tree.

**Comment by sanjaymsh** [comment]
@seth-priya openjdk9 & 10 is working fine on both of the arch. I will close this PR and raise new as there is issue in accessing the repository.

**Pull request closed without merging**
