### PR TITLE
Create codeready-workspaces.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Created package specific travis file and added support for ppc64le.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
I think "mvn clean install" itself is running the test also. Do we need "mvn test" again ? Rest all LGTM

**Comment by nageshlop** [comment]
@gururajrkatti yes, just included if in future additional tests are added.

**Comment by gururajrkatti** [comment]
> @gururajrkatti yes, just included if in future additional tests are added.

I think its repeating the same tests ? Is it not duplication ?

**Comment by nageshlop** [comment]
Ok I will remove "mvn test".

**Comment by nageshlop** [comment]
Updated travis.yml file and squashed.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
