### PR TITLE
Added bluebird.travis.yml

### PR DESCRIPTION
**Pull request by sanjaymsh**
Hi,

I have added bluebird.travis.yml, The travis log can be seen here https://travis-ci.com/github/sanjaymsh/bluebird/builds/213266891. Please review and merge.

Thanks !!

### CODE REVIEW

**Comment by sanjaymsh** [comment]
Another bonzo.travis.yml also added here only in the same PR.

**Review by gururajrkatti — COMMENTED** [review]
Not able to access the repository. Also do not combine multiple repos in a single PR.

**Comment by sanjaymsh** [comment]
> Not able to access the repository. Also do not combine multiple repos in a single PR.

Hi @gururajrkatti It got added by mistake. Then i thought, Its Ok. Anyway i will separate each other.
Thanks !!

**Comment by sanjaymsh** [comment]
closing as there is issue in accessing the repo. Will raise another PR.

**Pull request closed without merging**
