### PR TITLE
Create ibm-cos-sdk-java_ubuntu_20.04.sh

### PR DESCRIPTION
**Pull request by nageshlop**
Created package specific build script and verified the build on local vm.

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Hi Nagesh, script looks good to me. I suggest you update the test logs in the PR that shows the jar file being created. Can you pl. squash the commits

**Comment by nageshlop** [comment]
@gururajrkatti  I am working on below package as part of this other related jars get generated.

**Comment by nageshlop** [comment]
97 data-engine-api-1.1.20190923.jar 1.1.201909 https://github.com/odpi/egeria

**Comment by nageshlop** [comment]
Ok Done.

**Comment by nageshlop** [comment]
ubuntu@nagesh-at:/scratch/jar-proj/maven-rep/ibm-cos-sdk-java$ find . -name "ibm-cos-java-sdk-bundle"
./ibm-cos-java-sdk-bundle

Build Logs:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< com.ibm.cos:ibm-cos-java-sdk-bundle >-----------------
[INFO] Building IBM COS SDK for Java - Bundle 2.9.1
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.pom (9.5 kB at 9.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.jar (114 kB at 425 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk/2.9.1/ibm-cos-java-sdk-2.9.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk/2.9.1/ibm-cos-java-sdk-2.9.1.pom (3.5 kB at 27 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk-s3/2.9.1/ibm-cos-java-sdk-s3-2.9.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk-s3/2.9.1/ibm-cos-java-sdk-s3-2.9.1.pom (4.4 kB at 32 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk-s3/2.9.1/ibm-cos-java-sdk-s3-2.9.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk/2.9.1/ibm-cos-java-sdk-2.9.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk/2.9.1/ibm-cos-java-sdk-2.9.1.jar (2.2 kB at 6.6 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/com/ibm/cos/ibm-cos-java-sdk-s3/2.9.1/ibm-cos-java-sdk-s3-2.9.1.jar (895 kB at 2.3 MB/s)
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ibm-cos-java-sdk-bundle ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ ibm-cos-java-sdk-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ibm-cos-java-sdk-bundle ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ ibm-cos-java-sdk-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ ibm-cos-java-sdk-bundle ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ ibm-cos-java-sdk-bundle ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/target/ibm-cos-java-sdk-bundle-2.9.1.jar
[INFO]
[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ ibm-cos-java-sdk-bundle ---
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0_BETA/asm-commons-6.0_BETA.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0_BETA/asm-commons-6.0_BETA.pom (2.1 kB at 13 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.0_BETA/asm-tree-6.0_BETA.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.0_BETA/asm-tree-6.0_BETA.pom (2.1 kB at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/1.2/jdependency-1.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/1.2/jdependency-1.2.pom (11 kB at 51 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0_BETA/asm-analysis-6.0_BETA.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0_BETA/asm-analysis-6.0_BETA.pom (2.1 kB at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0_BETA/asm-util-6.0_BETA.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0_BETA/asm-util-6.0_BETA.pom (2.1 kB at 13 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0_BETA/asm-commons-6.0_BETA.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.0_BETA/asm-tree-6.0_BETA.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/1.2/jdependency-1.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0_BETA/asm-analysis-6.0_BETA.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0_BETA/asm-util-6.0_BETA.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0_BETA/asm-commons-6.0_BETA.jar (51 kB at 305 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.0_BETA/asm-tree-6.0_BETA.jar (34 kB at 194 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0_BETA/asm-analysis-6.0_BETA.jar (21 kB at 70 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/1.2/jdependency-1.2.jar (22 kB at 72 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0_BETA/asm-util-6.0_BETA.jar (47 kB at 138 kB/s)
[INFO] Including com.ibm.cos:ibm-cos-java-sdk:jar:2.9.1 in the shaded jar.
[INFO] Including com.ibm.cos:ibm-cos-java-sdk-s3:jar:2.9.1 in the shaded jar.
[INFO] Including com.ibm.cos:ibm-cos-java-sdk-kms:jar:2.9.1 in the shaded jar.
[INFO] Excluding javax.annotation:javax.annotation-api:jar:1.3.1 from the shaded jar.
[INFO] Including com.ibm.cos:ibm-cos-java-sdk-core:jar:2.9.1 in the shaded jar.
[INFO] Excluding javax.xml.bind:jaxb-api:jar:2.3.0 from the shaded jar.
[INFO] Excluding com.sun.xml.bind:jaxb-core:jar:2.3.0 from the shaded jar.
[INFO] Excluding com.sun.xml.bind:jaxb-impl:jar:2.3.0 from the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.3 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.13 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.4.13 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.11 in the shaded jar.
[INFO] Including software.amazon.ion:ion-java:jar:1.2.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.12.1 in the shaded jar.
[INFO] Including joda-time:joda-time:jar:2.8.2 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/target/ibm-cos-java-sdk-bundle-2.9.1.jar with /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/target/ibm-cos-java-sdk-bundle-2.9.1-shaded.jar
[INFO] Dependency-reduced POM written at: /scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle/target/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.503 s
[INFO] Finished at: 2021-05-13T14:19:53Z
[INFO] ------------------------------------------------------------------------
ubuntu@nagesh-at:/scratch/jar-proj/maven-rep/ibm-cos-sdk-java/ibm-cos-java-sdk-bundle$

**Pull request merged**
