### PR TITLE
Created a document containing build steps for tektoncd-CLI

### PR DESCRIPTION
**Pull request by vrushalid**
Created a document containing build steps for tektoncd-CLI.

### CODE REVIEW

**Comment by ghatwala** [comment]
@vrushalid  - can u please upload the license file to "tektoncd"  (squashing as 1 commit ideally ) directory as present in other directories.

**Comment by vrushaliinamdar** [comment]
> @vrushalid - can u please upload the license file to "tektoncd" (squashing as 1 commit ideally ) directory as present in other directories.

Done. Please check.

**Comment by ghatwala** [comment]
Please squash these 2 commits as 1  

>  (squashing as 1 commit ideally )

**Comment by vrushaliinamdar** [comment]
done squash

**Comment by ghatwala** [comment]
now this PR is showing 4 commits ...we ideally need just 1 commit . Guess would make sense if u raise a fresh PR with just one commit

**Pull request closed without merging**
