### PR TITLE
Create error-prone.travis.yml

### PR DESCRIPTION
**Pull request by gururajrkatti**

### CODE REVIEW

**Comment by seth-priya** [comment]
@Siddhesh-Ghadi please review

**Comment by Siddhesh-Ghadi** [comment]
Any particular reason for not testing other `jdk` versions on power? @gururajrkatti

**Comment by gururajrkatti** [comment]
Hi @Siddhesh-Ghadi when I was checking earlier,  openjdk12, openjdk13, openjdk14 etc.. were internally making use of openjdk11 itself on travis. Let me check it again

**Comment by gururajrkatti** [comment]
Hi @Siddhesh-Ghadi I have added openjdk8 (since oraclejdk8 not available)., openjdk12, openjdk14 and openjdk-ea and run the jobs. You can check th logs at https://travis-ci.com/github/gururajrkatti/error-prone/jobs/501902886.  Let me know if it is fine. Note that "openjdk-ea" fails with the error " E: Unable to locate package adoptopenjdk-ea-hotspot". If it is fine I will submit the new code and squash

**Comment by Siddhesh-Ghadi** [comment]
Lets exclude `openjdk-ea` job on power. Rest looks good. Thanks @gururajrkatti

**Comment by gururajrkatti** [comment]
Thanks @Siddhesh-Ghadi, have made the changes and squashed the commits

**Comment by Siddhesh-Ghadi** [comment]
Ready for merge @seth-priya

**Pull request merged**
