### PR TITLE
Added buildscript for scipy

### PR DESCRIPTION
**Pull request by vathsalashetty25**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [x] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by vathsalashetty25** [comment]
The remaining 3 patches already present in the repo under scipy..so not added them in this PR

**Comment by seth-priya** [comment]
@kumarvikas2020 please review

**Comment by kumarvikas2020** [comment]
@vathsalashetty25 
Please check mark the **Legal approvals** box in the checklist as we already have the approvals.

The old script and the new scripts vary only in places where we need to apply the patch files. Could you merge all these scripts together with **if** condition based on versions.

**Comment by vathsalashetty25** [comment]
Updated the script with required changes.

**Comment by seth-priya** [comment]
@kumarvikas2020 please check if this is good to merge?

**Comment by kumarvikas2020** [comment]
@seth-priya LGTM

**Pull request merged**
