### PR TITLE
Create readline.travis.yml

### PR DESCRIPTION
**Pull request by gururajrkatti**

### CODE REVIEW

**Review by seth-priya — COMMENTED** [review]
don't we have any unit test cases to be executed to be here?

**Comment by gururajrkatti** [comment]
> don't we have any unit test cases to be executed to be here?

README file doesn't mention about any specific tests. Build docker file in build_scripts includes "make install" in addition to the steps used in travis. Should it be included in travis ?

**Comment by seth-priya** [comment]
can you check if there is a "check" or "test" target in the Makefile?

**Comment by gururajrkatti** [comment]
> can you check if there is a "check" or "test" target in the Makefile?

"check" target is there. But it is empty. "make check" doesn't do anything. No "test" target.

**Comment by seth-priya** [comment]
ok thanks

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
