### PR TITLE
Added power support for the travis.yml file with ppc64le

### PR DESCRIPTION
**Pull request by sreekanth370**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing.

### CODE REVIEW

**Review by seth-priya — APPROVED** [review]

**Review by seth-priya — CHANGES_REQUESTED** [review]
The file location is wrong, please check and update

**Comment by sreekanth370** [comment]
file location updated correctly  . kindly check it .

**Comment by seth-priya** [comment]
@sreekanth370  please squash the commits.

**Comment by sreekanth370** [comment]
Hi Priya, 
squash the multiple commits . kindly review it ..

**Comment by sreekanth370** [comment]
i have done the squash commits , kindly check it ..

**Comment by sreekanth370** [comment]
i have done the squash commits , please  look it .

**Comment by sreekanth370** [comment]
kindly review my updates .

**Comment by sreekanth370** [comment]
tag @gururajrkatti

**Pull request merged**
