### PR TITLE
Delete javatuples.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
There is not file submitted here @nageshlop. Pl, submit the file

**Comment by nageshlop** [comment]
@gururajrkatti its regarding PR https://github.com/ppc64le/build-scripts/pull/496 which is having conflict with merge. Hence it is planned to remove and created the new PR for the same. This PR will remove the file.

**Comment by gururajrkatti** [comment]
@seth-priya I don't see anything to be reviewed here in this PR. The file shows as "deleted" no contents/diffs shown. Could you pl. clarify,

**Comment by seth-priya** [comment]
yeah, so since it is being deleted , that is what is expected no diffs, the file will go away completely after this is merged.

**Comment by nageshlop** [comment]
@seth-priya ready to merge.

**Pull request merged**
