### PR TITLE
Create verdaccio.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**
Created verdaccio.travis.yml and added support for amd64 and ppc64le

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Are there no tests here ?

**Comment by gururajrkatti** [comment]
Any updates on this ?

**Comment by dthadi3** [comment]
On node(15.x) and 15 versions one test case is failing on both amd64 and ppc64le
On remaining versions upto 14 & lts/* all test cases are passed
Should I write code for allow_failures for both 15 and node(15.x) or else update the code with 13, 14 & lts/*(14.x)
waiting for your suggestions.

**Comment by gururajrkatti** [comment]
yes, you can put the node in allow_failures and make sure there is an open issue for the failure

**Review by gururajrkatti — APPROVED** [review]
ok. Pl. ensure there is open issue for the common failure (across platform)

**Pull request merged**
