### PR TITLE
Create rdma-core.travis.yml

### PR DESCRIPTION
**Pull request by ddeka2910**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
I don't see any tests being run. Can you pl. try "make test" or "make check"

**Comment by ddeka2910** [comment]
The commands "make test" and "make check" doesn't trigger any test.
However the "build.sh" script seems to be performing some tests as can be seen in the log. Could you please verify the same and confirm.

**Comment by gururajrkatti** [comment]
There is "tests" folder in the repos. Can you pl. check if any of them are being run ?

**Comment by ddeka2910** [comment]
@gururajrkatti Tried pytest. But it is giving errors.

**Comment by gururajrkatti** [comment]
We need to check what are the errors

**Comment by seth-priya** [comment]
The testing itself has not happened as per the comments above, so substantial rework would be needed if someone else needs to pick this up, closing the PR as a fresh one would make more sense

**Pull request closed without merging**
