### PR TITLE
Knative upstream components v0.19.x build scripts added

### PR DESCRIPTION
**Pull request by VijayKumarHP**
Created scripts for Install/Test Knative packages (Serving, Eventing, net-istio, net-kourier, event-contrib & client ) for respective version and placed under the directory v0.18.x and v0.19.x .

### CODE REVIEW

**Comment by seth-priya** [comment]
@pratham-m please review, thanks

**Comment by pratham-m** [comment]
@VijayKumarHP 
1. Kindly add license info in all the scripts.
Reference: https://github.com/ppc64le/build-scripts/blob/master/k/knative/v0.16.x/knative-serving_0.16.0_rhel_7.6.sh#L7
2. Specify OS version (like Ubuntu 18.04) against "Tested on" in all scripts

Rest looks good.

**Comment by pratham-m** [comment]
@VijayKumarHP thanks for the changes
@seth-priya LGTM

**Comment by seth-priya** [comment]
thanks @pratham-m , @VijayKumarHP can you please squash the commits?

**Comment by VijayKumarHP** [comment]
@seth-priya It's showing only one commit at the HEAD under the feature branch (knative19) since i have edited all files in the Github GUI ,hence not able to squash in this case.  Please let me know if i need to raise a fresh PR with single commit.

**Pull request merged**
