### PR TITLE
Dockerfiles and build instructions for Eclipse-che workspace images.

### PR DESCRIPTION
**Pull request by nailushapotnuru**

### CODE REVIEW

**Comment by ghatwala** [comment]
@nailushapotnuru - also can you please squash into a single commit instead of having 8 commits going into main tree.

**Comment by nailushapotnuru** [comment]
> @nailushapotnuru - also can you please squash into a single commit instead of having 8 commits going into main tree.

`done`

**Comment by ghatwala** [comment]
@nailushapotnuru - not sure its done , still see 8 commits in here ?

**Comment by nailushapotnuru** [comment]
Hi Ghatwala,

Could you please check the below link. This is the commit which contains
all the 8 commits.
https://github.com/ppc64le/build-scripts/pull/144/commits/244118520aea7b1886e044ffea6700dd2d7be880

Thanks & Regards,
Nailusha

**Comment by ghatwala** [comment]
hi @nailushapotnuru  - i dont want 8 commits for this PR , just need a single commit , for example take a look here at this merged PR done by @bivasda1 - https://github.com/ppc64le/build-scripts/pull/149 which has all the code changes reflected in single commit.

**Comment by ghatwala** [comment]
closing this PR  in favor of https://github.com/ppc64le/build-scripts/pull/150

**Pull request closed without merging**
