### PR TITLE
AddPowerSupport_For_Create from2

### PR DESCRIPTION
**Pull request by santosh653**
creating from2.travis.yml with proposed changes.

### CODE REVIEW

**Comment by santosh653** [comment]
@Siddhesh-Ghadi @seth-priya Can you please review this PR?

**Review by gururajrkatti — COMMENTED** [review]
Any specific reason for choosing only upto node14 ?

**Comment by santosh653** [comment]
@gururajrkatti Node_js versions are supported between 4 to 15.
So just running the code on Most recent or Latest version of node_js.
Thanks !!

**Comment by santosh653** [comment]
@Siddhesh-Ghadi @seth-priya Can you please review this PR & Merge?

**Comment by santosh653** [comment]
@gururajrkatti @Siddhesh-Ghadi Can you pl review?

**Comment by gururajrkatti** [comment]
You can use "node" and "lts/*" for the latest versions

**Comment by santosh653** [comment]
@gururajrkatti Included lts/* & node in the code as per your review comments., 
Also squashed the commits.
Thank you !!

**Review by gururajrkatti — COMMENTED** [review]
Changes look good. Pl. check why loopback-component-push is coming in this commit

**Comment by santosh653** [comment]
@gururajrkatti l have included the code changes in the from2.travis file in the PR opened & then squashed the commits on patch-32 which is to be merged in to "master", Am I missing something?

**Comment by santosh653** [comment]
@gururajrkatti Can you pl review?

**Comment by seth-priya** [comment]
@santosh653 I see two travis.ymls in this PR, is that intentional because description refers to only one?

**Comment by santosh653** [comment]
@seth-priya I have deleted the 2nd travis file which got added by mistake.
Squashed the commits, Kindly check & confirm.,

**Comment by santosh653** [comment]
@seth-priya @gururajrkatti Can you please review?

**Comment by Siddhesh-Ghadi** [comment]
Ready for merge @seth-priya

**Pull request merged**
