### PR TITLE
Added build script for svg-sanitizer

### PR DESCRIPTION
**Pull request by SunidhiGaonkar**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@vedang-wartikar please review

**Comment by vedang-wartikar** [comment]
looks like there are merge conflicts due to #2047 get merged first. @SunidhiGaonkar can you please see if that build script is reusable, else push another script for this version

**Comment by vedang-wartikar** [comment]
looks like there are merge conflicts due to #2047 get merged first. @SunidhiGaonkar can you please see if that build script is reusable, else push another script for this version

**Comment by seth-priya** [comment]
@SunidhiGaonkar please raise another PR if needed, closing this as redundant

**Pull request closed without merging**
