### PR TITLE
Adding script for maistra/envoy

### PR DESCRIPTION
**Pull request by NishikantThorat**
- Added power support for (maistra 2.2)envoy

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@rashmi-ibm  please review

**Comment by rashmi-ibm** [comment]
the script looks fine, changes can be merged.
cc: @seth-priya @kandarpamalipeddi

**Comment by seth-priya** [comment]
ok, thanks seems @kandarpamalipeddi is looking at the travis check failure, will wait for that to passt.

**Comment by NishikantThorat** [comment]
> @NishikantThorat & @rashmi-ibm As Travis job is failing due to the time error, I tried running it on my VM(in fact container). I found below error :
```
> ERROR: Config value 'ppc64le' is not defined in any .rc file
```

@kandarpamalipeddi : Taken care in this [commit](https://github.com/ppc64le/build-scripts/pull/2359/commits/6033e451666343367b5bdaf3ecd97c4f18a8de53)

**Comment by kandarpamalipeddi** [comment]
With `--config=ppc` build is working fine.

```
[1229/1240] STAMP obj/v8_compiler_for_mksnapshot.stamp
[1230/1240] STAMP obj/v8_init.stamp
[1231/1240] LINK ./mksnapshot
[1232/1240] CXX obj/wee8/c-api.o
[1233/1240] ACTION //:run_mksnapshot_default(//build/toolchain/linux/unbundle:default)
[1234/1240] STAMP obj/run_mksnapshot_default.stamp
[1235/1240] STAMP obj/v8_snapshot.inputdeps.stamp
[1236/1240] CXX obj/v8_snapshot/setup-isolate-deserialize.o
[1237/1240] ASM obj/v8_snapshot/embedded.o
[1238/1240] CXX obj/v8_snapshot/snapshot.o
[1239/1240] STAMP obj/v8_snapshot.stamp
[1240/1240] AR obj/libwee8.a
/root/.cache/bazel/_bazel_root/bd7c8cff91ab88f7eebbbebfd072b029/sandbox/processwrapper-sandbox/3071/execroot/envoy
Target //source/exe:envoy-static up-to-date:
  bazel-bin/source/exe/envoy-static
INFO: Elapsed time: 6705.982s, Critical Path: 1138.06s
INFO: 4208 processes: 135 internal, 4072 processwrapper-sandbox, 1 worker.
INFO: Build completed successfully, 4208 total actions
```

**Review by kandarpamalipeddi — APPROVED** [review]

**Pull request merged**
