### PR TITLE
angular:bldscript

### PR DESCRIPTION
**Pull request by ankitpar**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@ankitpar 
1- Please check the relevant fields in the checklist above
2- do we know why the travis build is failing?

**Comment by ankitpar** [comment]
checking for failure on local script is success

**Comment by seth-priya** [comment]
@ankitpar as mentioned above, please investigate and fix the travis build failures (cc @kandarpamalipeddi @prashantkhoje )

**Review by kandarpamalipeddi — CHANGES_REQUESTED** [review]
1.  I can see 3 yum install npm in this script. Do we really need them ?
2. Yum install npm version 10.x, but it is always good to go with npm >12 (unless any package have hard dependency on the npm version).
3. At the end, you are using `npm install --save angularjs-toaster`, as far as I know, it will try to get the latest version available for the angularjs-toaster (I see that as 3.0.0), so we are not  installing the required version (1.2.0).
4. Even if it worked, here it is simply installing the latest version, but we are not validating the code. Please check the `.travis.yaml` file for further details.

**Comment by seth-priya** [comment]
@ankitpar any update?

**Comment by ankitpar** [comment]
> 1. I can see 3 yum install npm in this script. Do we really need them ?
> 2. Yum install npm version 10.x, but it is always good to go with npm >12 (unless any package have hard dependency on the npm version).
> 3. At the end, you are using `npm install --save angularjs-toaster`, as far as I know, it will try to get the latest version available for the angularjs-toaster (I see that as 3.0.0), so we are not  installing the required version (1.2.0).
> 4. Even if it worked, here it is simply installing the latest version, but we are not validating the code. Please check the `.travis.yaml` file for further details.

Hi @seth-priya @kandarpamalipeddi fixed all the comments local build has passed.

**Comment by ankitpar** [comment]
Build is only failing on travis due to connection issue.

**Comment by seth-priya** [comment]
This script is installing the latest version of the package from the npm registry instead of building/installing and validating from source , this will need to be re-created / re-worked

**Pull request closed without merging**
