### PR TITLE
commit for logstash package

### PR DESCRIPTION
**Pull request by saraswati-patra**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by kandarpamalipeddi** [comment]
Hello @saraswati-patra, 

Build script validation is failing due to End of Line character.
Looks like, you generated build script on Widnows machine and committed it.
Please use Unix End of Line, otherwise script can't be validated by Travis-job.

**Comment by saraswati-patra** [comment]
rerun updated EOL Unix machine

**Comment by saraswati-patra** [comment]
rerun updated EOL Unix machine

**Review by kandarpamalipeddi — CHANGES_REQUESTED** [review]
Looks like this is not logstash.
This is logstash plugin, can you please create a new directory for this script ?

**Comment by seth-priya** [comment]
@saraswati-patra  any update on this?

**Comment by saraswati-patra** [comment]
> @saraswati-patra any update on this?

@Priya,
logstash-filter-geoip already merged and it is in respective directory.logstash supposed to close not yet need to close that.thanks

**Pull request closed without merging**
