### PR TITLE
Add architecture ppc64le to travis build

### PR DESCRIPTION
**Pull request by ddeka2910**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
@ddeka2910 "Source Repo" in the header is pointing to something else. Can you pl. modify it

**Comment by ddeka2910** [comment]
Updated the travis file.

**Review by gururajrkatti — COMMENTED** [review]
Pl. squash the commits. Everything else LGTM

**Comment by ddeka2910** [comment]
Squashed the commits

**Comment by gururajrkatti** [comment]
Not sure why is the commit "Serverless and KN CLI midstream build scripts added" appearing in this. Pl. check

**Comment by ddeka2910** [comment]
Closing this to open a new PR.

**Pull request closed without merging**
