### PR TITLE
Create connect.travis.yml

### PR DESCRIPTION
**Pull request by genisysram**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
node10 is supported on ppc64le. Whats the reason it's excluded ?

**Comment by genisysram** [comment]
Hi 
I have ran for version node js 10.19 version and it has failing with the reason" npm WARN deprecated debug@3.2.6"

since its a low severity is issue they have not given any fix and ignored since less people were effected with this particular version.
for more details we can look through ("https://github.com/visionmedia/debug/issues/797")

So I have removed the particular version and made the test passed.

**Comment by genisysram** [comment]
@gururajrkatti

**Comment by gururajrkatti** [comment]
I think deprecation is a just a warning. It wouldn't have caused failure. Pl. check the error and also if it needs to be excluded, pl. add the appropriate comment to the .travis.yml file

**Comment by genisysram** [comment]
@gururajrkatti 
Thanks for the suggestion, I ran in local and updated travis file according.

**Comment by gururajrkatti** [comment]
Thanks. Could you pl. squash the commits

**Comment by genisysram** [comment]
@gururajrkatti 
Squashed all the commits please look into this PR

**Comment by Siddhesh-Ghadi** [comment]
Ready for merge @seth-priya

**Pull request merged**
