### PR TITLE
Dockerfile for custodia

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

This is build is working and tested. Please review it.

image

Thanks

### CODE REVIEW

**Review by gerrith3 — COMMENTED** [review]
@seth-priya do we usually reference a private github repository for the build, or do we cherry pick the patches needed and pull from the original github URL?  I would think the latter makes most sense, especially when Eshant returns to his regular day job.  Also, Eshant, did you try to get this patch accepted by the custodia community?  I don't remember seeing it, and that is the "ideal" path (although not always possible).

**Comment by seth-priya** [comment]
agreed @gerrith3 - the "ideal" option is to get the patch accepted. If that does not get accepted or get delayed for whatever reasons, we generally create and upload the patch file to this repo. such that it resides next to the build script or dockerfile and can be directly applied - that removes any dependency on private fork.

**Comment by ezeeyahoo** [comment]
Here is merged PR https://github.com/latchset/custodia/pull/249

**Comment by seth-priya** [comment]
ok, cool - so in that case we should be able to just clone the official tree in your dockerfile as opposed to the private fork, I believe?

**Comment by ezeeyahoo** [comment]
I think I have done some mistake. I will open a new PR

**Pull request closed without merging**
