### PR TITLE
merging two repos

### PR DESCRIPTION
**Pull request by genisysram**

### CODE REVIEW

**Review by seth-priya — CHANGES_REQUESTED** [review]
Please follow the correct file naming convention for "connect"

**Comment by ghatwala** [comment]
also @genisysram  - can you please squash all commits in this PR to a single commit. ?

**Comment by genisysram** [comment]
@seth-priya 
Please merge this PR

**Comment by seth-priya** [comment]
@genisysram I still see 7 commits in here, please squash

**Review by seth-priya — CHANGES_REQUESTED** [review]
The location of this file is wrong, it should be under the travis-ymls folder

**Review by seth-priya — COMMENTED** [review]
There seems to be an issue with the commit, not sure why libqb is showing up?

**Comment by genisysram** [comment]
Closing this PR , as it becoming complex moving forward, raising individual prs for reach repo.

**Pull request closed without merging**
