### PR TITLE
Created Build_katib.sh

### PR DESCRIPTION
**Pull request by ujjwalsh**
Added Build script for Katib.sh Please check

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@ezeeyahoo can u pl. review

**Review by ezeeyahoo — APPROVED** [review]

**Review by seth-priya — COMMENTED** [review]
Please add Apache 2.0 license file

**Comment by gururajrkatti** [comment]
@ujjwalsh Any updates on this ?

**Comment by seth-priya** [comment]
@gajanankulkarni-18 please review and raise a fresh PR and close.

**Comment by seth-priya** [comment]
Closing for now, @gajanankulkarni-18  to raise a fresh PR

**Pull request closed without merging**
