### PR TITLE
Create resolve.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**
Created travis.yml and added Travis-ci support for ppc64le and amd64

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Comment by nageshlop** [comment]
@dthadi3 Please verify whether the package support latest and lts node versions. If so you can add the same. Further details can be found at PR https://github.com/ppc64le/build-scripts/pull/537.

**Comment by dthadi3** [comment]
@nageshlop Done with requested changes.

**Review by nageshlop — APPROVED** [review]

**Comment by nageshlop** [comment]
@gururajrkatti and @seth-priya LGTM.

**Pull request merged**
