### PR TITLE
Adding power support by CI

### PR DESCRIPTION
**Pull request by asellappen**
few jobs not inculded since ppa (ppa:libreoffice/ppa) does not have the Power LE packages

### CODE REVIEW

**Comment by asellappen** [comment]
pls note only 4 files are changed/added under folder travis-ymls  with PR and
overrides.travis.yml was removed which was wrongly added in parent folder https://github.com/asellappen/build-scripts

**Comment by asellappen** [comment]
new yml file  added for python-semver in the same PR

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
1. You have added ```arch:
  - amd64
  - ppc64le``` and it also has job matrix. This is causing unnecssary jobs. Pl. check and correct. 2. 2. Also I seem some job failures here ?
3. What's the reason for adding "notificaitons" ?

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
1. mvn install is being run multiple times and same tests are being repeated. Pl. check and correct it. 
2. You can as well use jdk11 (its internally using jdk11 anyway)

**Comment by asellappen** [comment]
> 1. You have added ```arch:
> 
> * amd64
> * ppc64le``` and it also has job matrix. This is causing unnecssary jobs. Pl. check and correct. 2. 2. Also I seem some job failures here ?
> 
> 1. What's the reason for adding "notificaitons" ?

pls mentioned the yml to check further

**Comment by asellappen** [comment]
> 1. mvn install is being run multiple times and same tests are being repeated. Pl. check and correct it.
> 2. You can as well use jdk11 (its internally using jdk11 anyway)

pls mentioned the yml to check further

**Comment by asellappen** [comment]
> 1. You have added ```arch:
> 
> * amd64
> * ppc64le``` and it also has job matrix. This is causing unnecssary jobs. Pl. check and correct. 2. 2. Also I seem some job failures here ?

removed arch  part and only matrix job extended for ppc now ,and failures are are on intel ,The same jobs are also failed at ppc due to the reason not supporting  ppa (ppa:libreoffice/ppa),Hence not include these jobs job in matrix and made note there now.
> 
> 1. What's the reason for adding "notificaitons" ?
It looks notification part was recently removed from github master itself about a week ago and forked the package about a week hence missing  latest change,taken care in our PR also now.


pl review now

**Comment by asellappen** [comment]
> > 1. mvn install is being run multiple times and same tests are being repeated. Pl. check and correct it.

This is the way the packages  are working since long ,Please refer  https://travis-ci.org/github/codehaus-plexus/plexus-compiler/jobs/754581469, It was the job part of previous PR by community, So do not want to disturb flow and will follow the same. 
> > 2. You can as well use jdk11 (its internally using jdk11 anyway)
modified yml to change to jdk11 now 


pls verify.

**Comment by gururajrkatti** [comment]
> > 1. You have added ```arch:
> > 
> > 
> > * amd64
> > * ppc64le``` and it also has job matrix. This is causing unnecssary jobs. Pl. check and correct. 2. 2. Also I seem some job failures here ?
> 
> removed arch part and only matrix job extended for ppc now ,and failures are are on intel ,The same jobs are also failed at ppc due to the reason not supporting ppa (ppa:libreoffice/ppa),Hence not include these jobs job in matrix and made note there now.
> 
> > 1. What's the reason for adding "notificaitons" ?
> >    It looks notification part was recently removed from github master itself about a week ago and forked the package about a week hence missing  latest change,taken care in our PR also now.
> 
> pl review now

Pl. add the new travis job link also in the modified files so that they reflect correct matrix and logs.

**Comment by gururajrkatti** [comment]
> > > 1. mvn install is being run multiple times and same tests are being repeated. Pl. check and correct it.
> 
> This is the way the packages are working since long ,Please refer https://travis-ci.org/github/codehaus-plexus/plexus-compiler/jobs/754581469, It was the job part of previous PR by community, So do not want to disturb flow and will follow the same.
> 
> > > 1. You can as well use jdk11 (its internally using jdk11 anyway)
> > >    modified yml to change to jdk11 now
> 
> pls verify.

**Comment by gururajrkatti** [comment]
Looks like plexus-compiler.travis.yml newly added. Pl. do not add any more files to this PR. 
Notification still present in pyramid_chameleon.travis.yml. pypy3 included here for ppc. You can remove it since its not supported.

**Comment by asellappen** [comment]
done,Pls check now

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Could you pl. squash all the commits

**Comment by asellappen** [comment]
> Could you pl. squash all the commits

made to single commit

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Pull request merged**
