### PR TITLE
Updated ppc64le arch to travis.yml to plexus-io

### PR DESCRIPTION
**Pull request by rajesh-ibm-power**
Updated ppc64le arch to travis.yml  to plexus-io package

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@santosh653 can you pl. review this

**Comment by santosh653** [comment]
@rajesh-ibm-power I think you have updated openjdk7 to openjdk11 that is fine as long as it is running fine on recent one.
LGTM

**Review by santosh653 — APPROVED** [review]
LGTM

**Comment by santosh653** [comment]
@gururajrkatti looks fine, I think I approved this PR by mistake.,

**Pull request merged**
