### PR TITLE
Build script for pyyaml

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

PR: Not accepted
Build Script: will follow later

Please review.

Thanks

### CODE REVIEW

**Review by gerrith3 — COMMENTED** [review]
@ezeeyahoo I'd like @seth-priya to confirm, but I don't think we typically pull from what may be a "transient" directory, e.g. your personal github repository.  Of course, getting the patches accepted upstream is the first resort, but if that doesn't work, I'd prefer to see us cherry pick the change, included it as another file in your directory within the build scripts and pull that when doing a build.

**Comment by seth-priya** [comment]
yes, right - a patch in the same directory, private forks don't make sense

**Comment by seth-priya** [comment]
@ezeeyahoo any update on this?

**Comment by ezeeyahoo** [comment]
Not accepted yet, but now is the time to write script.

**Comment by ezeeyahoo** [comment]
Done and tested. Please review.

**Comment by seth-priya** [comment]
Closing due to lack of response

**Pull request closed without merging**
