### PR TITLE
Added power support for package xarray

### PR DESCRIPTION
**Pull request by asellappen**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Looks like only doctest-modules are being tested. Is it not possible to run all tests ?

**Comment by asellappen** [comment]
> Looks like only doctest-modules are being tested. Is it not possible to run all tests ?

Included unit test also now ,There are some test modules are not supported for both arch .
pl check now.

**Comment by gururajrkatti** [comment]
Travis job link is point to cancelled build. Could you pl. mention the correct job link in the file.

**Comment by asellappen** [comment]
> Travis job link is point to cancelled build. Could you pl. mention the correct job link in the file.

Due to credit issue ,it was blocked &cancelled.Triggered again ,Pl check now.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
