### PR TITLE
Added build-script,build-info.json for parquet-mr

### PR DESCRIPTION
**Pull request by vinodk99**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@nikhil-kalbande

**Comment by nikhil-kalbande** [comment]
@vinodk99 why package name is blank in build_info.json

**Comment by vinodk99** [comment]
> @vinodk99 why package name is blank in build_info.json

Updated the build_info.json

**Review by nikhil-kalbande — APPROVED** [review]

**Review by nikhil-kalbande — APPROVED** [review]

**Comment by seth-priya** [comment]
@vinodk99 please update the license file for this one as well

**Comment by vinodk99** [comment]
> @vinodk99 please update the license file for this one as well

Updated the license file.

**Pull request merged**
