### PR TITLE
Redis 6.2.4 ubi8 image

### PR DESCRIPTION
**Pull request by snehakpersistent**
Redhat ubi8 image for Redis 6.2.4

### CODE REVIEW

**Comment by seth-priya** [comment]
@kandarpamalipeddi please review

**Comment by kandarpamalipeddi** [comment]
@snehakpersistent 

One suggestion, Can you rename the `r/redis/Dockerfiles/latest_ubi_8/` to `r/redis/Dockerfiles/6.2.4_ubi_8/`
Rest looks good to me.

Thanks.

**Comment by snehakpersistent** [comment]
@kandarpamalipeddi Updated. @seth-priya can we proceed to merge this?

**Review by ghatwala — APPROVED** [review]
LGTM

**Pull request merged**
