### PR TITLE
build script for Zstd-jni

### PR DESCRIPTION
**Pull request by dthadi3**

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Review by nageshlop — CHANGES_REQUESTED** [review]
The script should accept the tag or branch as an argument and should build master or any versions of supported tags being passed. And it should build default version, if we don't pass any argument, as per the requirement.

Could you make appropriate changes in script to include these. Also verify it is generating jar file after build and update the build logs in comment section. For further details check the PR's that are accepted and closed by others.

**Comment by nageshlop** [comment]
@dthadi3

**Comment by gururajrkatti** [comment]
@dthadi3 any updates on this ?

**Comment by dthadi3** [comment]
having some dependency issues with this package now... so closing this PR.


[info] Resolved  dependencies
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.joprice:sbt-jni:0.2.2-SNAPSHOT (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.joprice:sbt-jni;sbtVersion=1.0;scalaVersion=2.12:0.2.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/joprice/sbt-jni_2.12_1.0/0.2.2-SNAPSHOT/sbt-jni-0.2.2-SNAPSHOT.pom
[error]   not found: /root/.ivy2/local/com.github.joprice/sbt-jni/scala_2.12/sbt_1.0/0.2.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.joprice/sbt-jni/scala_2.12/sbt_1.0/0.2.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.joprice/sbt-jni/scala_2.12/sbt_1.0/0.2.2-SNAPSHOT/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)

**Pull request closed without merging**
