### PR TITLE
AddingPowerSupport_flask-restful

### PR DESCRIPTION
**Pull request by santosh653**
Creating flask-restful.travis.yml with proposed changes.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Should we not retain 2.7 as that is the only python supported in python2 ?

**Comment by santosh653** [comment]
@gururajrkatti I think we are ok if the code runs fine on python3 versions, there were failures on python2.7, I confirm on this from my previous interactions with Priya.

**Comment by santosh653** [comment]
@gururajrkatti Can you pl review?

**Comment by gururajrkatti** [comment]
Are the same failures found on intel also ?

**Comment by santosh653** [comment]
@gururajrkatti , Yes Guru, there were similar failures on both Intel & power. That's why we are good here I think.

**Review by gururajrkatti — APPROVED** [review]
ok

**Review by santosh653 — COMMENTED** [review]
@seth-priya Can you please merge this PR now?

**Pull request merged**
