### PR TITLE
Adding version info in script pear_archivetar

### PR DESCRIPTION
**Pull request by vathsalashetty25**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@kumarvikas2020 please review

**Review by kumarvikas2020 — CHANGES_REQUESTED** [review]
line 22 to 24 - This logic is already covered in line 20, so can be removed.
line 25 - Avoid using yum update command.
line 33 - exit statement is missing with proper exit code.
line 40 - in case of failure it should be exit 1
line 50 - in case of failure it should be exit 1

**Comment by vathsalashetty25** [comment]
Updated the script with required changes

**Comment by seth-priya** [comment]
@kumarvikas2020 please confirm changes

**Review by kumarvikas2020 — APPROVED** [review]

**Pull request merged**
