### PR TITLE
added folder and build scripts and  jwt-utils_ubuntu_18.04.sh

### PR DESCRIPTION
**Pull request by asellappen**

### CODE REVIEW

**Comment by asellappen** [comment]
Downloading and installing node v12.18.3...
Downloading https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-ppc64le.tar.xz...
############################################################################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v12.18.3 (npm v6.14.6)
Creating default alias: default -> 12.18.3 (-> v12.18.3)
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

+ jest@26.6.3
added 520 packages from 361 contributors and audited 521 packages in 41.163s

24 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

added 1 package from 1 contributor and audited 522 packages in 4.753s

24 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> @around25/jwt-utils@1.0.1 test /jwt-utils
> jest

 PASS  tests/Token.test.js



Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.863 s
Ran all test suites.

**Comment by gururajrkatti** [comment]
Is it created jwt-utils*.jar as per the requirement ?

**Comment by asellappen** [comment]
> Is it created jwt-utils*.jar as per the requirement ?

no , It isn't created , I think that there is supposed to be an entry in the file package.json for creating jar in npm build and test.

**Comment by asellappen** [comment]
> Is it created jwt-utils*.jar as per the requirement ?





> > Is it created jwt-utils*.jar as per the requirement ?
> 
> no , It isn't created , I think that there is supposed to be an entry in the file package.json for creating jar in npm build and test.

further investigation ,I have checked few npm related build scripts under ppc64le/build-scripts path n/node* and there are npm used to build ,but i am not able to figure out jar files created for them anywhere(ran at vm). In our case ,build completed successfully,  we are expecting jar file jwt-utils-0.2.4.jar and not created ,And the same not specified anywhere in  package.json. 

@seth-priya / @Siddhesh-Ghadi ,Can you help  ?

**Pull request closed without merging**
