### PR TITLE
Created jung.travis.yml

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Created jung.travis.yml in the PR. Please review

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Comment by nageshlop** [comment]
Except below typo in travis file, rest LGTM.
# Per https://docs.travis-ci.com/user/languages/java

**Comment by seth-priya** [comment]
@kishorkunal-raj any update on this?

**Comment by kishorkunal-raj** [comment]
> @kishorkunal-raj any update on this?

Yeah @seth-priya , The comment which is pointed by @nageshlop already present in the existing travis.yml  and is not been added by me. So please suggest either to keep or remove it from the jung.travis.yml file

**Comment by gerrith3** [comment]
Generally speaking, fix any typos or minor problems.  I couldn't figure out what the typo was here.  Also, we don't have oracle jdk on Power so make sure that gets excluded on Power builds.

**Comment by kishorkunal-raj** [comment]
@seth-priya The file is ready to merge after excluding the jobs for oracle jdk on power as suggested by @gerrith3. Please review

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
