### PR TITLE
Create createHmac.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**
Created createHmac.travis.yml and added support for power and amd64.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
I see that travis.yml already exists for this. In this case the header should mention it as not created right ?

**Comment by gururajrkatti** [comment]
ok, pl. squash the commits

**Comment by dthadi3** [comment]
@gururajrkatti Requested changes done.

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Pull request merged**
