### PR TITLE
Add build script for masitra/proxy v2.5

### PR DESCRIPTION
**Pull request by Chandranana**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by Chandranana** [comment]
[log_proxy_build.txt](https://github.com/user-attachments/files/16095211/log_proxy_build.txt)

**Comment by Swapnali911** [comment]
Adding container logs for proxy maistra-2.5 
[maista_2.5_proxy_container.log](https://github.com/user-attachments/files/16156519/maista_2.5_proxy_container.log)

**Comment by prasanna-marathe** [comment]
@Chandranana  Latest tag is `2.5.2`  Reference: [tags](https://github.com/maistra/proxy/tags). However branch added by you is `maistra-2.5` 
Request to run code with latest release/tag and share logs

**Comment by prasanna-marathe** [comment]
@Chandranana Request to add reason to use `ubi8.9`  image instead of ubi9.3 in comments somewhere in build script Thanks

**Comment by Chandranana** [comment]
> @Chandranana Latest tag is `2.5.2` Reference: [tags](https://github.com/maistra/proxy/tags). However branch added by you is `maistra-2.5` Request to run code with latest release/tag and share logs

@prasanna-marathe The midstream scripts are not latest specific and **we build only major releases** hence tag is 2.5. 2.5.2 is minor release.

**Comment by Chandranana** [comment]
> Latest Golang version is `1.22` But script only mentions about `1.20`. Can we check with latest Golang and update results. Can we also create variable like GO_VERSION so that we can avoid hard coding in code and will help to maintain script in better way.

@prasanna-marathe Will add Go_VERSION variable to script. but checking with latest go version is really needed? Because in sometime again new go version will be released. At the time of verification for v2.5 proxy we have verified with 1.20.x .

Also next version of proxy 2.6 requires 1.21 go version.

**Comment by prasanna-marathe** [comment]
> > Latest Golang version is `1.22` But script only mentions about `1.20`. Can we check with latest Golang and update results. Can we also create variable like GO_VERSION so that we can avoid hard coding in code and will help to maintain script in better way.
> 
> @prasanna-marathe Will add Go_VERSION variable to script. but checking with latest go version is really needed? Because in sometime again new go version will be released. At the time of verification for v2.5 proxy we have verified with 1.20.x .
> 
> Also next version of proxy 2.6 requires 1.21 go version.

Yes it would be better to check with latest golang version. Not require to update Golang version then for longer duration

**Comment by Chandranana** [comment]
Attaching logs for the build for updated script 
[Log_proxy_2.5_updated.txt](https://github.com/user-attachments/files/16408967/Log_proxy_2.5_updated.txt)

**Comment by prasanna-marathe** [comment]
Approved

**Review by prasanna-marathe — APPROVED** [review]
Approved

**Comment by prasanna-marathe** [comment]
This repo will only goto build script and CI will not be enabled for this.

**Pull request merged**
