### PR TITLE
Travis-ci: added support for ppc64le & update go 15, node

### PR DESCRIPTION
**Pull request by dthadi3**
I had added ppc64le(Linux on Power) architecture support on Travis-CI in the PR.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Pl. put some comments in the travis file mentioning the reason for removing node 4,6 and 8

**Comment by dthadi3** [comment]
changed the title with info, Is this be ok.

**Comment by gururajrkatti** [comment]
Hi @dthadi3 you need to comments inside the yml file

**Comment by dthadi3** [comment]
@gururajrkatti Done with requested change, please have a look.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
