### PR TITLE
Created travis.yml for package nestedSortable

### PR DESCRIPTION
**Pull request by rajesh-ibm-power**
Created travis.yml for package nestedSortable

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Same as 462. npm test is not running anything

**Comment by gururajrkatti** [comment]
@rajesh-ibm-power Pl. refer #462. Use node and lts/* also

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
updated with node and lts/*

**Comment by gururajrkatti** [comment]
Pl. update the travis log location and squash the commits.

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
Multiple commit has been squash and traavis job link pointing to sucess build

**Comment by gururajrkatti** [comment]
what is the reason for adding the step "cd meteor" now ?

**Comment by rajesh-ibm-power** [comment]
Hi @gururajrkatti 

script:
 - cd meteor
Above command will resolve the test case failed for node version in prior tests i.e.
Error message : The command "npm test" exited with 1. 
Travis url : https://travis-ci.com/github/rajesh-ibm-power/nestedSortable/jobs/482128033
Test script location : https://github.com/rajesh-ibm-power/nestedSortable/tree/master/meteor

**Comment by gururajrkatti** [comment]
Is it not better to put it in allow_failures than masking it so that it will be useful in future also ?

**Comment by gururajrkatti** [comment]
Any updates on this

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti updated with allowed failure,  Kindly verify.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
