### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by rpsene**
Add Dockerfile to build Redis 6.2 using RH UBI8

### CODE REVIEW

**Review by gerrith3 — COMMENTED** [review]
Does redis depend on tcl or can it be removed after building as well?  Other than that looks good to me.

**Comment by seth-priya** [comment]
I think it is the redis test suite that is written in tcl, so it more like a dev dependency and probably can be removed, @rpsene ?

**Comment by gerrith3** [comment]
@rpsene do you have any feedback on this?  Trying to trim our backlog on github pull requests!  thanks!

**Comment by rpsene** [comment]
@snehakpersistent is this in your TODO list?

**Comment by snehakpersistent** [comment]
@rpsene no it wasn't. Let me know if you want me to build/test it.

**Comment by gerrith3** [comment]
@snehakpersistent remember the goal is to see what can/should be removed from the container before publishing.  Usually that includes any developer tools that aren't needed at runtime.  The goal is to keep the container as small as possible (but no smaller).  Thanks!

**Comment by snehakpersistent** [comment]
This PR can be closed. Redis 6.2.4 ubi8 image changes has been merged in PR [946](https://github.com/ppc64le/build-scripts/pull/946).

**Pull request closed without merging**
