### PR TITLE
Added power support for the travis.yml file with ppc64le.

### PR DESCRIPTION
**Pull request by sreekanth370**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing

### CODE REVIEW

**Comment by seth-priya** [comment]
@Siddhesh-Ghadi please review

**Comment by Siddhesh-Ghadi** [comment]
You have removed unsupported node versions directly from matrix: https://github.com/sreekanth370/nan/commit/ae3d9172b326f28b8a71fe475a8d29db80b81ceb

Lets not directly remove unsupported versions on power instead exclude it so that we don't  disturb the build matrix on amd64.

**Comment by sreekanth370** [comment]
dropped unsupported node versions on power arch  node 0.10, 0.12 to nan.travis.yml.

**Comment by Siddhesh-Ghadi** [comment]
Please squash the commits. Rest all looks good. Thanks @sreekanth370

**Comment by sreekanth370** [comment]
unfortunately deleted the branch travis.yml. hence closing

**Pull request closed without merging**
