### PR TITLE
Arumugam work branch package dask glm

### PR DESCRIPTION
**Pull request by asellappen**

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@santosh653 can you pl. review this

**Comment by asellappen** [comment]
> @santosh653 can you pl. review this
@santosh653,Anby update on this pl.

**Comment by santosh653** [comment]
@asellappen I am seeing the build as cancelled in the Travis link., with the given Travis link in travis.yml file.
Kindly correct me if wrong,
Also, Can we include python2.7 also to verify the build on python2. 'nightly' can also be included.

**Comment by asellappen** [comment]
> @asellappen I am seeing the build as cancelled in the Travis link., with the given Travis link in travis.yml file.
> Kindly correct me if wrong,
> Also, Can we include python2.7 also to verify the build on python2. 'nightly' can also be included.
@santosh653,
-had short of credit during that time and was cancelled somehow , Now I ran and completed successfully.

- not sure why do we need older version here ,Moreover this package/dependencies are supporting above py3.6 only ,And also check github action CI which includes only 3.7 currently, but i have added 3.8 also to make sure to cover forth coming versions.

-And also now i have modified the yml to avoid time out issues ,to include python version installation on conda which was missing earlier, pl review now.

**Review by santosh653 — APPROVED** [review]
LGTM

**Pull request merged**
