### PR TITLE
Add build-script and dockerfile for cockroach v20.1.0

### PR DESCRIPTION
**Pull request by amitsadaphule**

### CODE REVIEW

**Comment by amitsadaphule** [comment]
@ghatwala or @seth-priya please review.

**Review by seth-priya — COMMENTED** [review]
@amitsadaphule can we also explicitly call out the known issues / workarounds in the README with reference to appropriate CocroachDB GitHub issues?

**Comment by amitsadaphule** [comment]
Right, missed that. Thanks!

**Comment by amitsadaphule** [comment]
Pushed the update. Updated file: c/cockroachdb/v20.1.0-oss/README.md

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
