### PR TITLE
Updated build-scripts with suggested changes.

### PR DESCRIPTION
**Pull request by varsha-aaynure**
Updated build-scripts with suggested changes.

### CODE REVIEW

**Comment by seth-priya** [comment]
@varsha-aaynure  (cc @kandarpamalipeddi ) I am not sure I get the intention of this PR?

**Comment by varsha-aaynure** [comment]
@seth-priya, this PR is for the build-scripts of the EventStreams packages on which i've worked.

CC: @kandarpamalipeddi

**Comment by seth-priya** [comment]
ok, haven't these been raised as part of other PRs already and I see a lot of conflicts in above?

**Comment by varsha-aaynure** [comment]
Yes, some of the PRs got merge already that needs minor changes.

**Pull request closed without merging**
