### PR TITLE
zap version v1.15.0 test and validate successfully

### PR DESCRIPTION
**Pull request by stutiibm**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Review by seth-priya — COMMENTED** [review]
@stutiibm are the build instructions same as that of the previously available script? if so we should update the existing script, if not, we should have only the current version specified here

**Comment by stutiibm** [comment]
> @stutiibm are the build instructions same as that of the previously available script? if so we should update the existing script, if not, we should have only the current version specified here

Yes, I made the required changes in same script.

**Comment by seth-priya** [comment]
But I see, two scripts zap_ubi_8.5.sh
 and zap_v1.15.0.sh, the latter being the one you are adding with this commit?

**Comment by stutiibm** [comment]
> But I see, two scripts zap_ubi_8.5.sh and zap_v1.15.0.sh, the latter being the one you are adding with this commit?

Yes , Please merge zap_v1.15.0.sh

**Pull request closed without merging**
