### PR TITLE
Travis-CI: Added support power & updated node_js 12 & 14

### PR DESCRIPTION
**Pull request by dthadi3**
I had added ppc64le(Linux on Power) architecture support & updated node_js 12 & 14 versions on Travis-CI in the PR.

### CODE REVIEW

**Comment by dthadi3** [comment]
@seth-priya Please review this PR.

**Review by seth-priya — COMMENTED** [review]
do we want to enable the notifications ?

**Comment by dthadi3** [comment]
@seth-priya We can disable them, if not required. Do you want me to remove that notifications?

**Comment by seth-priya** [comment]
Yes, that would make sense

**Comment by dthadi3** [comment]
@seth-priya Done with requested changes.

**Pull request merged**
