### PR TITLE
Create node-rdkafka.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**
Added support to power.

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
It doesn't seem to be running anything. Have you run it on local machine ?

**Comment by dthadi3** [comment]
yes @gururajrkatti community also replied with same if they write the proper code its ok otherwise, I'll try write the code for all arch's so it will take some time.

**Comment by seth-priya** [comment]
@dthadi3 any update?

**Comment by dthadi3** [comment]
@seth-priya  looking into it... will give an update or try to complete before next week.

**Comment by dthadi3** [comment]
@seth-priya @gururajrkatti 
There is code fix for this repo, but not yet merged by the community 
https://github.com/Blizzard/node-rdkafka/pull/861
once it's got merged, we can work on this.

**Comment by dthadi3** [comment]
@gururajrkatti As already mentioned, if we need to write the proper travis.yml there should required lot more code changes in the package as referred in the above comment.

**Comment by dthadi3** [comment]
If not you can handover this package to anyone.... Thanks in advance

**Comment by seth-priya** [comment]
Requires substantial rework, closing as stale

**Pull request closed without merging**
