### PR TITLE
Create nekohtml-1.9.13.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Updated build.xml and created travis.yml to support travis build and ppc64le support.

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Are there no tests in this repos ?

**Comment by nageshlop** [comment]
@gururajrkatti in build.xml there are pointers to junit test. Let me know if any specific commands that I have to include or run and verify.

**Comment by gururajrkatti** [comment]
Did you try "ant test" or "ant run" ?

**Comment by nageshlop** [comment]
The ant run and test fails.
Log:
ubuntu@nagesh-at:/scratch/travis-job/nekohtml-1.9.13$ ant run
Buildfile: /scratch/travis-job/nekohtml-1.9.13/build.xml

BUILD FAILED
Target "run" does not exist in the project "null".

Total time: 0 seconds
ubuntu@nagesh-at:/scratch/travis-job/nekohtml-1.9.13$

**Review by gururajrkatti — APPROVED** [review]
ok

**Comment by nageshlop** [comment]
@seth-priya  ready to merge.

**Pull request merged**
