### PR TITLE
Create JsonSurfer_ubuntu_20.04.sh

### PR DESCRIPTION
**Pull request by santosh653**
Adding build script with the 1.5.1.jar, The Build is successful with the 1.5.1.jar., 

Results :

Tests run: 449, Failures: 0, Errors: 0, Skipped: 1

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jsurfer-all ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/ubuntu/JsonSurfer/JsonSurfer/jsurfer-all/target/jsurf                                                                                        er-all-1.5.1.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jsurfer-all ---
[INFO] Installing /home/ubuntu/JsonSurfer/JsonSurfer/jsurfer-all/target/jsurfer-                                                                                        all-1.5.1.jar to /home/ubuntu/.m2/repository/com/github/jsurfer/jsurfer-all/1.5.                                                                                        1/jsurfer-all-1.5.1.jar
[INFO] Installing /home/ubuntu/JsonSurfer/JsonSurfer/jsurfer-all/pom.xml to /hom                                                                                        e/ubuntu/.m2/repository/com/github/jsurfer/jsurfer-all/1.5.1/jsurfer-all-1.5.1.p                                                                                        om
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JsonSurfer 1.5.1:
[INFO]
[INFO] JsonSurfer ......................................... SUCCESS [  2.198 s]
[INFO] jsurfer-core ....................................... SUCCESS [ 25.589 s]
[INFO] jsurfer-gson ....................................... SUCCESS [  0.829 s]
[INFO] jsurfer-jackson .................................... SUCCESS [  0.983 s]
[INFO] jsurfer-jsonsimple ................................. SUCCESS [  0.968 s]
[INFO] jsurfer-fastjson ................................... SUCCESS [  0.233 s]
[INFO] jsurfer-all ........................................ SUCCESS [  8.731 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.827 s
[INFO] Finished at: 2021-06-22T05:05:52Z
[INFO] ------------------------------------------------------------------------
ubuntu@santoshkulkarni:~/JsonSurfer$ ./JsonSurfer-ubumtu_20.04.sh v1.5.1

### CODE REVIEW

**Comment by santosh653** [comment]
[LICENSE.txt](https://github.com/ppc64le/build-scripts/files/6693390/LICENSE.txt)
Adding License File

**Comment by gururajrkatti** [comment]
Pl. do a spellcheck in the file name. Also use underscore instead of dash to maintain consistency with other scripts. Rest all LGTM

**Comment by santosh653** [comment]
@seth-priya @gururajrkatti , Hi Done the needful as per review comments, please do the needul.

**Review by gururajrkatti — APPROVED** [review]
ok

**Comment by santosh653** [comment]
@seth-priya Can you please merge this PR?

**Comment by santosh653** [comment]
@seth-priya Can you pl approve this PR?

**Comment by amitsadaphule** [comment]
@santosh653 please add LICENSE file. It is missing in the commit.

**Pull request merged**
