### PR TITLE
Adding scripts for multiple Katib/suggestion components 

### PR DESCRIPTION
**Pull request by pranavpandit1**
These changes are intended for multiple katib/suggestion components.

### CODE REVIEW

**Comment by seth-priya** [comment]
So @pranavpandit1 couple of quick things
- we should have 1 script per GitHub URL, so if you have multiple components that map to the exact same GitHub tree, you should be creating only one script 
- we should have only 1 script in a single PR

**Comment by pranavpandit1** [comment]
@seth-priya : I am okay with creating a single script, but from KF's perspective these are all different images.
kindly suggest.

**Comment by seth-priya** [comment]
@pranavpandit1  lets stick to single script

**Comment by pranavpandit1** [comment]
Closing this PR as all the components will be integrated in a single script. raising another PR.

**Pull request closed without merging**
