### PR TITLE
Added build script for httpsnippet.

### PR DESCRIPTION
**Pull request by bhagat-singh001**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by bhagat-singh001** [comment]
closing pull request for rerun as it not reflecting status after even 4 days.

**Comment by bhagat-singh001** [comment]
Reopening pull request for rerun.

**Comment by seth-priya** [comment]
@nikhil-kalbande lets consider this for currency, close this PR once we raise a new one, we should try with latest version as community is active

**Comment by nikhil-kalbande** [comment]
Added to currency tracker to do list. Closing this PR.

**Pull request closed without merging**
