### PR TITLE
Create yaml.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Created travis file which supports ppc64le and verified the changes with build and test.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Let's use latest node as mentioned in #537

**Comment by nageshlop** [comment]
@gururajrkatti updated as per the suggestion in PR https://github.com/ppc64le/build-scripts/pull/500. @seth-priya could you clarify.

**Comment by seth-priya** [comment]
@nageshlop does the package support latest and lts node versions? if so, we should move fwd. with @gururajrkatti 's suggestion

**Comment by nageshlop** [comment]
@gururajrkatti @seth-priya please review. Made necessary changes to include latest node versions and its working fine.

**Pull request merged**
