### PR TITLE
Added Dockerfile for Redis UBI build

### PR DESCRIPTION
**Pull request by redmark-alt**
Note that the Ubuntu Docker file has `checkout 3.2.9` but I found that the latest is `3.2.13`.

### CODE REVIEW

**Comment by redmark-alt** [comment]
I've also provide better updates to the README.md file.

**Comment by seth-priya** [comment]
Looks, good, we may need some additional changes for clearing the certification, but they can be in a subsequent PR, thanks!

**Comment by redmark-alt** [comment]
@here I understand the non-root requirement is needed.  I recommend we process `this` pull request so we don't start stacking commits on top of each other.  It makes the reviews harder to read and understand... unless we `squash commits` which I can do if that is our process.

**Comment by redmark-alt** [comment]
@seth-priya Sorry, I was typing my comment and your were closing the PR.

**Pull request merged**
