### PR TITLE
Create minimal-json.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Added support for ppc64le.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
What is the reason for using jdk11 for amd and jdk8 for ppc ? Also you don't include it and then exclude it, you can have one include job for amd and one for ppc

**Comment by nageshlop** [comment]
@gururajrkatti Its not openjdk11 its oraclejdk11 which is part of existing travis.yml and runs on amd64 architecture and the same is excluded for ppc64le as its not supported. Hence, I have added openjdk8 for ppc64le which is supported.

**Comment by gururajrkatti** [comment]
You don't need to include it and then exclude it

**Comment by nageshlop** [comment]
@gururajrkatti oraclejdk11 is added for amd64 and excluded for ppc64le as it is not supported.

**Comment by nageshlop** [comment]
@gururajrkatti can you review, updated the travis.yml file to remove exclude part and verified the changes with build and test.

**Review by gururajrkatti — APPROVED** [review]
ok

**Comment by nageshlop** [comment]
@seth-priya  ready to merge.

**Pull request merged**
