### PR TITLE
Created travis.yml for package history.js

### PR DESCRIPTION
**Pull request by rajesh-ibm-power**
Created travis.yml for package history.js

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
npm test is returning back with "no test specified". @seth-priya  pl. confirm if it is okay to close this without any testing.

**Comment by seth-priya** [comment]
@gururajrkatti yes, that generally means that the package does not have any automated tests, in which case it is okay to move fwd.

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
@rajesh-ibm-power  can you pl. add lts/* and node also. For all repos where we are adding new travis file, we should test for these latest versions

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
Updated travis.yml file with node and lts/*. Travis url :https://travis-ci.com/github/rajesh-ibm-power/history.js

**Comment by gururajrkatti** [comment]
Ok. Update the location in the file and squash the commits

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
multiple commit has been squashed and travis job link pointing to latest sucess build kindly review

**Comment by gururajrkatti** [comment]
what is the reason "cd tests" done now instead of "npm test" ?

**Comment by rajesh-ibm-power** [comment]
Hi @gururajrkatti 

script:
 - cd tests
Above command will resolve the test case failed for node version in prior tests.
Test script location : https://github.com/rajesh-ibm-power/history.js/tree/master/tests

**Comment by gururajrkatti** [comment]
Is it not better to put it in allow_failures than masking it so that it will be useful in future also ?

**Comment by gururajrkatti** [comment]
Any updates on this ?

**Comment by seth-priya** [comment]
@rajesh-ibm-power any update?

**Comment by rajesh-ibm-power** [comment]
@seth-priya Update with allowed failure to travis.yml. squash and commit has been done

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
