### PR TITLE
elasticsearch version 7.11 on ubi8 image

### PR DESCRIPTION
**Pull request by Elayaraja-Dhanapal**
RedHat UBI 8 image with elasticsearch version 7.11

### CODE REVIEW

**Comment by seth-priya** [comment]
@junawaneshivani please review.

**Comment by junawaneshivani** [comment]
@Elayaraja-Dhanapal Can you please add the Openshift testing steps to the README ?
You can refer to this https://github.com/ppc64le/build-scripts/tree/master/e/elasticsearch/Dockerfiles/7.8.0_centos_7#deployment-on-openshift

**Comment by Elayaraja-Dhanapal** [comment]
@junawaneshivani updated README accordingly. Please review.

**Comment by junawaneshivani** [comment]
LGTM!

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
