### PR TITLE
Stan.go v0.10.2

### PR DESCRIPTION
**Pull request by reynold-vazp**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by reynold-vazp** [comment]
@Siddhesh-Ghadi @vedang-wartikar

**Comment by Siddhesh-Ghadi** [comment]
Is `p/python-bunyan/python-bunyan_ubi_8.5.sh` script to be added with this PR? @reynold-vazp

**Comment by reynold-vazp** [comment]
> Is `p/python-bunyan/python-bunyan_ubi_8.5.sh` script to be added with this PR? @reynold-vazp

No

**Comment by reynold-vazp** [comment]
Not sure how its appearing here

**Review by kandarpamalipeddi — APPROVED** [review]

**Pull request merged**
