### PR TITLE
Updated buildscript for sinon-chai

### PR DESCRIPTION
**Pull request by saurabhghumnar**
Updated the script addressing review comments in [#1220](https://github.com/ppc64le/build-scripts/pull/1220)

### CODE REVIEW

**Comment by saurabhghumnar** [comment]
@Siddhesh-Ghadi please review

**Comment by Siddhesh-Ghadi** [comment]
Update the script to resolve basic validation failure. Check CI job for more details.

**Comment by saurabhghumnar** [comment]
@Siddhesh-Ghadi resolved validation failure. Please review

**Review by Siddhesh-Ghadi — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
