### PR TITLE
Currency: Added build_script,build_info and patch for rstudio-Server[v2024.09.0+375].

### PR DESCRIPTION
**Pull request by gauravpbankar13**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [x] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by gauravpbankar13** [comment]
All test cases are passing for ppc64le, but some below errors are appearing for both x86 and ppc64le.

```
ERROR system error 37 (No locks available) [lock-file: /tmp/rstudio-test-lock]; O                          CCURRED AT virtual rstudio::core::Error rstudio::core::LinkBasedFileLock::acquire(const rstudio::core::FilePath&) src/cpp/core                          /file_lock/LinkBasedFileLock.cpp:532; LOGGED FROM: void rstudio::core::tests::C_A_T_C_H_T_E_S_T_0() /tmp/rstudio/src/cpp/core/                          FileLockTests.cpp:9
ERROR Invalid indicator on port token 'fb7559983669'.; LOGGED FROM: int rstudio::server_core::detransformPort(const string&, const string&, bool&) src/cpp/server_core/UrlPorts.cpp:138
2024-11-13T05:31:22.193214Z [rstudio-tests-] ERROR Unexpected exception: stoull; LOGGED FROM: int rstudio::server_core::detransformPort(const string&, const string&, bool&) src/cpp/server_core/UrlPorts.cpp:145
```

**Comment by gauravpbankar13** [comment]
Hi @vinodk99 :
Can you please review it?

**Review by vinodk99 — COMMENTED** [review]
update the package_name and package_dir to rstudio

**Review by vinodk99 — CHANGES_REQUESTED** [review]
update the version argument on line 12 as per version you specified

**Comment by gauravpbankar13** [comment]
> update the package_name and package_dir to rstudio

Updated as per suggested.

**Comment by gauravpbankar13** [comment]
> update the version argument on line 12 as per version you specified

Updated as per suggested

**Comment by gauravpbankar13** [comment]
@vinodk99 :
Any other changes are required?

**Comment by gauravpbankar13** [comment]
Hi @nikhil-kalbande 
Vinod has reviewed the code, if require can you also review it and merge it?

**Comment by vinodk99** [comment]
@gauravpbankar13  update the PACKAGE_NAME=rstudio in build-script also and use that PACKAGE_NAME variable after cloning the repo

**Comment by gauravpbankar13** [comment]
> @gauravpbankar13 update the PACKAGE_NAME=rstudio in build-script also and use that PACKAGE_NAME variable after cloning the repo

Updated

**Review by nikhil-kalbande — APPROVED** [review]

**Pull request merged**
