### PR TITLE
Adding base, base-jave, JVB UBI images for Jitsi

### PR DESCRIPTION
**Pull request by kandarpamalipeddi**

### CODE REVIEW

**Comment by seth-priya** [comment]
@kandarpamalipeddi are all of these files (.conf and Makefile etc.) required to be uploaded along with the Dockerfiles?

**Comment by kandarpamalipeddi** [comment]
Makefile, 99local, apt-cleanup & apt-dpkg-wrap are not required for UBI, rest are required.
Thanks for pointing, will remove them.

**Comment by kandarpamalipeddi** [comment]
@seth-priya 
Can you please review and merge changes ?

**Comment by seth-priya** [comment]
@kandarpamalipeddi do we want to keep the ".gitkeep" files?

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
