### PR TITLE
AddingPowerSupport_json-smart

### PR DESCRIPTION
**Pull request by santosh653**
creating json-smart.travis.yml with proposed changes.,

### CODE REVIEW

**Review by seth-priya — CHANGES_REQUESTED** [review]
We should either try to root cause the issue for jdk 7 and 8 for amd64 (preferable if the community is active and responsive) or else for consistency just run for 11 (and / or higher) for all architectures

**Comment by santosh653** [comment]
I am running here the code for oraclejdk11 for both the arch's

**Comment by seth-priya** [comment]
Please squash the commits @santosh653

**Comment by santosh653** [comment]
@seth-priya I have squashed the commits, Can you please review?

**Comment by seth-priya** [comment]
@santosh653 I still see 2 commits, please squash

**Comment by santosh653** [comment]
I have squashed them, can you please review now..?
Apologies for confusion.

**Comment by seth-priya** [comment]
I still see 2 commits??

**Comment by santosh653** [comment]
I am closing this Pull Request for now.,

**Pull request closed without merging**
