### PR TITLE
Create quicklz.travis.yml

### PR DESCRIPTION
**Pull request by ddeka2910**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Are there no tests to run here ? Rest all LGTM

**Comment by ddeka2910** [comment]
There are no instruction for running tests in the README file.

**Comment by gururajrkatti** [comment]
Did you try "make test" or "make check" ?

**Comment by ddeka2910** [comment]
Yes tried both. But nothing gets triggered.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
