### PR TITLE
AddPowerSupport_python-rake

### PR DESCRIPTION
**Pull request by santosh653**
Creating python-rake.travis.yml with proposed changes.

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Add source comments mentioning the reason for excluding 2.7. Also you don't need to explicitly exclude if you are excluding for all platforms. You can simply remove it .

**Comment by santosh653** [comment]
@gururajrkatti I have modified the file as per your comments & squashed the commits, kindly verify now.

**Comment by santosh653** [comment]
@gururajrkatti Hi Guru, Can you pl review this??

**Comment by santosh653** [comment]
@gururajrkatti Kindly review,

**Review by gururajrkatti — APPROVED** [review]
ok

**Comment by santosh653** [comment]
@seth-priya Can you please merge this PR? It is approved.,

**Pull request merged**
