### PR TITLE
Create http-deceiver.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
node 6 is removed and node 5 included. Also "stable" is removed ? Pl. mention the reason as part of the comment in the travis file. Is it not possible to use "node" version for the latest stable release?

**Comment by dthadi3** [comment]
Even in the main repo build also node 6 and stable are failing.... so tried all supported versions for ppc64le including node, lts/*. Only passing on node versions 5 & 10. So that's the reason updated in the yml with 5 & 10.

**Comment by gururajrkatti** [comment]
> Even in the main repo build also node 6 and stable are failing.... so tried all supported versions for ppc64le including node, lts/*. Only passing on node versions 5 & 10. So that's the reason updated in the yml with 5 & 10.

Ok, you can add the same as part of comments in the yml

**Comment by dthadi3** [comment]
@gururajrkatti updated changes as requested.

**Review by gururajrkatti — APPROVED** [review]
ok

**Comment by dthadi3** [comment]
@seth-priya Can you please merge this PR.

**Pull request merged**
