### PR TITLE
Created jackson-core.travis.yml

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Created jackson-core.travis.yml in the PR. please review

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@ezeeyahoo can you pl. review this

**Comment by ezeeyahoo** [comment]
Looks fine to me.

**Comment by kishorkunal-raj** [comment]
@seth-priya this PR is similar to #571 which is closed. But still this PR is showing "resolve conflict". How can i resolve it as the option is disabled from my end.

**Comment by seth-priya** [comment]
This is a duplicate, the file https://github.com/ppc64le/build-scripts/blob/master/travis-ymls/jackson-core.travis.yml already exists in the repo.

**Pull request closed without merging**
