### PR TITLE
CreatigTravisFile_mock

### PR DESCRIPTION
**Pull request by santosh653**
Creating mock.travis.yml with proposed changes

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Review by nageshlop — CHANGES_REQUESTED** [review]
@santosh653 Can you verify with latest supported version of Python and also include test execution [ python setup.py test].

**Comment by santosh653** [comment]
@nageshlop Thanks for your comments.
I have included more recent Python versions along with running [ python setup.py test].
I have squashed the commits.

**Comment by nageshlop** [comment]
@gururajrkatti LGTM.

**Pull request merged**
