### PR TITLE
Create vscode-ripgrep.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Created travis file which supports ppc64le. Verified the changes with build and test.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
For all node .travis.yml which we create from scratch, lets test them on latest node versions also.
+    - node  #latest stable Node.js release
+    - lts/* #latest LTS Node.js release

**Comment by nageshlop** [comment]
@gururajrkatti updated as per the suggestion in PR https://github.com/ppc64le/build-scripts/pull/500. @seth-priya could you clarify.

**Comment by seth-priya** [comment]
@nageshlop does the package support latest and lts node versions? if so, we should move fwd. with @gururajrkatti 's suggestion

**Comment by nageshlop** [comment]
@gururajrkatti @seth-priya please review. The latest node version supported for the repo is 14 hence no changes. Added lts/* node release and verified the changes.

**Pull request merged**
