### PR TITLE
AddingBuildScript_org.aspectj

### PR DESCRIPTION
**Pull request by santosh653**
attaching the assembly file: /home/ubuntu/org.aspectj/org.aspectj/installer/target/aspectj-1.9.7.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ installer ---
[INFO] Installing /home/ubuntu/org.aspectj/org.aspectj/installer/target/aspectj-1.9.7.jar to /home/ubuntu/.m2/repository/org/aspectj/installer/1.9.7/installer-1.9.7.jar
[INFO] Installing /home/ubuntu/org.aspectj/org.aspectj/installer/target/flattened-pom.xml to /home/ubuntu/.m2/repository/org/aspectj/installer/1.9.7/installer-1.9.7.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for AspectJ Parent Project 1.9.7:
[INFO]
[INFO] AspectJ Parent Project ............................. SUCCESS [  0.851 s]
[INFO] lib ................................................ SUCCESS [  4.821 s]
[INFO] util ............................................... SUCCESS [  2.666 s]
[INFO] bridge ............................................. SUCCESS [  1.215 s]
[INFO] testing-util ....................................... SUCCESS [  1.094 s]
[INFO] org.aspectj.matcher ................................ SUCCESS [  5.555 s]
[INFO] asm ................................................ SUCCESS [  1.027 s]
[INFO] testing-client ..................................... SUCCESS [  0.854 s]
[INFO] runtime ............................................ SUCCESS [  1.485 s]
[INFO] bcel-builder ....................................... SUCCESS [  2.919 s]
[INFO] weaver ............................................. SUCCESS [ 20.407 s]
[INFO] org.aspectj.ajdt.core .............................. SUCCESS [ 18.649 s]
[INFO] ajde.core .......................................... SUCCESS [  7.379 s]
[INFO] ajde ............................................... SUCCESS [  6.896 s]
[INFO] ajbrowser .......................................... SUCCESS [  0.244 s]
[INFO] loadtime ........................................... SUCCESS [  2.816 s]
[INFO] ajdoc .............................................. SUCCESS [ 16.691 s]
[INFO] taskdefs ........................................... SUCCESS [  4.109 s]
[INFO] testing ............................................ SUCCESS [ 29.171 s]
[INFO] testing-drivers .................................... SUCCESS [ 54.397 s]
[INFO] tests .............................................. SUCCESS [12:17 min]
[INFO] build .............................................. SUCCESS [  1.326 s]
[INFO] run-all-junit-tests ................................ SUCCESS [  0.460 s]
[INFO] docs ............................................... SUCCESS [  0.631 s]
[INFO] AspectJ Runtime .................................... SUCCESS [  1.372 s]
[INFO] AspectJ Weaver ..................................... SUCCESS [  2.670 s]
[INFO] AspectJ Tools (Compiler) ........................... SUCCESS [ 13.304 s]
[INFO] AspectJ Matcher .................................... SUCCESS [  0.324 s]
[INFO] AspectJ Installer .................................. SUCCESS [  1.037 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:43 min
[INFO] Finished at: 2021-07-13T06:51:17Z
[INFO] ------------------------------------------------------------------------
ubuntu@santoshkulkarni:~/org.aspectj$

### CODE REVIEW

**Comment by seth-priya** [comment]
@gururajrkatti  please review, thanks

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Review by seth-priya — CHANGES_REQUESTED** [review]
The License file should have only the Apache 2.0 license and not the package (s) licenses. Keep in mind it is the license under which the script is published and not the license of the open source package(s) built as part of it

**Comment by santosh653** [comment]
@seth-priya Added the correct License File.

**Comment by seth-priya** [comment]
@santosh653 there are conflicts, plase resolve

**Comment by santosh653** [comment]
CLosing this PR as not able to delete the unwanted files

**Pull request closed without merging**
