### PR TITLE
Adding buildscript for carbon componenets for ubuntu 18.04

### PR DESCRIPTION
**Pull request by Manik-ibm**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [x] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by sumitd2** [comment]
All 4 scripts not working:

+ git checkout 10.9.1
error: pathspec '10.9.1' did not match any file(s) known to git.

**Comment by Manik-ibm** [comment]
Review comment incorporated.

**Comment by Manik-ibm** [comment]
Review comment incorporated.

**Comment by sumitd2** [comment]
All four scripts are look good and are running fine.
For the first 3, please list all the failing tests at the end of the scripts and mention they are in parity, as per new guidelines.

**Comment by sumitd2** [comment]
Can be merged

**Pull request merged**
