### PR TITLE
Create ruamel.yaml.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Can we run linters test also ? Rest all LGTM

**Comment by seth-priya** [comment]
@dthadi3 any update on this?

**Comment by dthadi3** [comment]
@seth-priya running linters test having some issue with that, so trying to debug and raised an issue for the community for the help will try to complete it ASAP.

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
LGTM. please squash the commits

**Pull request merged**
