### PR TITLE
Created travis.yml file for apiguardian-api

### PR DESCRIPTION
**Pull request by rajesh-ibm-power**
Created travis.yml file for package apiguardian-api

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Is "bash <(curl -s https://codecov.io/bash) " really required here ? Is it doing something useful ?
Rest all LGTM

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
bash command is not doing anything useful so removed and updated same

**Comment by gururajrkatti** [comment]
Pl. update the travis log location and squash the commits

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti 
Multiple commit has been squashed and travis job link pinting to success build, kindly review

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Pull request merged**
