### PR TITLE
Adding new yml to build on travis and support power for package PyMySQL

### PR DESCRIPTION
**Pull request by asellappen**
Adding new yml to build on travis and support power for package PyMySQL

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
test_auth.py doesn't have to be executed ?

**Comment by asellappen** [comment]
> test_auth.py doesn't have to be executed ?
not required ,Pls refer https://pymysql.readthedocs.io/en/latest/user/development.html.

**Comment by gururajrkatti** [comment]
Ok. I saw the other CI running it (https://github.com/PyMySQL/PyMySQL/blob/master/.github/workflows/test.yaml) hence wanted to clarify

**Comment by asellappen** [comment]
As discussed with @seth-priya , made mysql on ppc64le part to  allow failure as the docker mysql image is not actively working for ppc64le.pl review now.

**Comment by asellappen** [comment]
raised  issue ticket to community for  https://github.com/PyMySQL/PyMySQL/issues/975 for test script error in the file pymysql/tests/test_connection.py at line 449.

IF they ask raise PR and merge then will follow, Otherwise let them take care.

**Comment by asellappen** [comment]
@gururajrkatti changed the trasvis file as per discussion ,Pl review

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
