### PR TITLE
Created travis.yml for xerces-c package

### PR DESCRIPTION
**Pull request by rajesh-ibm-power**
Created travis.yml file for package xerces-c

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@rajesh-ibm-power There seems to be travis build failures here ?

**Comment by gururajrkatti** [comment]
@rajesh-ibm-power any updates on this?

**Comment by rajesh-ibm-power** [comment]
Hi @gururajrkatti,
Since travis.yml file is existed in this package and update done was adding ppc64le arch.

In both scenarions of travis build i.e. with existing travis.yml (https://travis-ci.com/github/rajesh-ibm-power/xerces-c/builds/216746883) and 
updated travis.yml for ppc64le arch (https://travis-ci.com/github/rajesh-ibm-power/xerces-c/builds/211020764). 
OSX build is failing in both scenario, need to update package handler for this.

**Comment by gururajrkatti** [comment]
ok, but the build location shown in the file points to the place where there are no ppc jobs

**Comment by seth-priya** [comment]
@rajesh-ibm-power any update on this?

**Comment by rajesh-ibm-power** [comment]
@seth-priya i have tested with both of the scenarios. 
And concluded with existing travis.yml and updated travis.yml file with ppc64le arch, That OSx failure need to be handle by package handler.

Updated travis.yml for ppc64le arch (https://travis-ci.com/github/rajesh-ibm-power/xerces-c/builds/211020764) 
Existing travis.yml (https://travis-ci.com/github/rajesh-ibm-power/xerces-c/builds/216746883)
kindly go through link

**Comment by gururajrkatti** [comment]
Hi @rajesh-ibm-power pl. update the travis link with ppc jobs in the yml file

**Comment by seth-priya** [comment]
@rajesh-ibm-power any update on this?

**Comment by seth-priya** [comment]
@rajesh-ibm-power looks like a simple request from @gururajrkatti , could you please address?

**Comment by rajesh-ibm-power** [comment]
@gururajrkatti I have updated Travis job link, kindly verify.
OSx is failing with and without including PPC64le arch and need to be taken care by package handler.

**Comment by gururajrkatti** [comment]
@rajesh-ibm-power one of the OSX jobs (Build=autoconf) is working fine as per https://travis-ci.org/github/apache/xerces-c/builds/698683963. Can you pl. check why is it failing in our job.

**Comment by rajesh-ibm-power** [comment]
Hi @gururajrkatti,
I have raised OSx build failure to package handler.
https://github.com/rajesh-ibm-power/xerces-c/commit/9f2c96f0368b4da867e32cbfbccc5e24f5f7f658
 
thnak you

**Comment by seth-priya** [comment]
Closing this as the review comments were not completely addressed

**Pull request closed without merging**
