### PR TITLE
AddingBuildScriptForJersey

### PR DESCRIPTION
**Pull request by santosh653**
[INFO] Building jar: /home/ubuntu/jersey/jersey/test-framework/maven/custom-enforcer-rules/target/custom-enforcer-rules-3.0.1.jar
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ custom-enforcer-rules ---
[INFO] Building jar: /home/ubuntu/jersey/jersey/test-framework/maven/custom-enforcer-rules/target/custom-enforcer-rules-3.0.1-sources.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ custom-enforcer-rules ---
[INFO] Installing /home/ubuntu/jersey/jersey/test-framework/maven/custom-enforcer-rules/target/custom-enforcer-rules-3.0.1.jar to /home/ubuntu/.m2/repository/org/glassfish/jersey/test-framework/maven/custom-enforcer-rules/3.0.1/custom-enforcer-rules-3.0.1.jar
[INFO] Installing /home/ubuntu/jersey/jersey/test-framework/maven/custom-enforcer-rules/pom.xml to /home/ubuntu/.m2/repository/org/glassfish/jersey/test-framework/maven/custom-enforcer-rules/3.0.1/custom-enforcer-rules-3.0.1.pom
[INFO] Installing /home/ubuntu/jersey/jersey/test-framework/maven/custom-enforcer-rules/target/custom-enforcer-rules-3.0.1-sources.jar to /home/ubuntu/.m2/repository/org/glassfish/jersey/test-framework/maven/custom-enforcer-rules/3.0.1/custom-enforcer-rules-3.0.1-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jersey 3.0.1:
[INFO]
[INFO] jersey ............................................. SUCCESS [ 8.660 s]
[INFO] jersey-archetypes .................................. SUCCESS [ 1.458 s]
[INFO] jersey-archetype-heroku-webapp ..................... SUCCESS [ 3.160 s]
[INFO] jersey-archetype-grizzly2 .......................... SUCCESS [ 0.322 s]
[INFO] jersey-archetype-webapp ............................ SUCCESS [ 0.324 s]
[INFO] jersey-example-java8-webapp ........................ SUCCESS [ 0.722 s]
[INFO] jersey-bom ......................................... SUCCESS [ 0.137 s]
[INFO] jersey-core-common ................................. SUCCESS [ 43.001 s]
[INFO] jersey-inject ...................................... SUCCESS [ 0.361 s]
[INFO] jersey-inject-hk2 .................................. SUCCESS [ 4.236 s]
[INFO] jersey-core-client ................................. SUCCESS [ 37.489 s]
[INFO] jersey-media ....................................... SUCCESS [ 0.225 s]
[INFO] jersey-media-jaxb .................................. SUCCESS [ 4.277 s]
[INFO] jersey-core-server ................................. SUCCESS [ 43.523 s]
[INFO] jersey-containers .................................. SUCCESS [ 0.643 s]
[INFO] jersey-container-grizzly2-http ..................... SUCCESS [ 2.458 s]
[INFO] jersey-container-servlet-core ...................... SUCCESS [ 6.537 s]
[INFO] jersey-test-framework .............................. SUCCESS [ 0.243 s]
[INFO] jersey-test-framework-core ......................... SUCCESS [ 5.993 s]
[INFO] jersey-container-servlet ........................... SUCCESS [ 0.678 s]
[INFO] jersey-container-grizzly2-servlet .................. SUCCESS [ 0.616 s]
[INFO] jersey-test-framework-providers .................... SUCCESS [ 0.208 s]
[INFO] jersey-test-framework-provider-grizzly2 ............ SUCCESS [ 12.046 s]
[INFO] jersey-connectors .................................. SUCCESS [ 0.200 s]
[INFO] jersey-connectors-apache ........................... SUCCESS [ 23.216 s]
[INFO] jersey-test-framework-provider-inmemory ............ SUCCESS [ 3.380 s]
[INFO] jersey-test-framework-provider-external ............ SUCCESS [ 0.255 s]
[INFO] jersey-container-jdk-http .......................... SUCCESS [ 19.022 s]
[INFO] jersey-test-framework-provider-jdk-http ............ SUCCESS [ 8.584 s]
[INFO] jersey-container-simple-http ....................... SUCCESS [ 18.001 s]
[INFO] jersey-test-framework-provider-simple .............. SUCCESS [ 2.641 s]
[INFO] jersey-connectors-netty ............................ SUCCESS [ 42.781 s]
[INFO] jersey-container-netty-http ........................ SUCCESS [ 0.572 s]
[INFO] jersey-test-framework-provider-netty ............... SUCCESS [ 0.300 s]
[INFO] jersey-container-jetty-http ........................ SUCCESS [ 3.487 s]
[INFO] jersey-test-framework-provider-jetty ............... SUCCESS [ 0.236 s]
[INFO] jersey-test-framework-provider-bundle .............. SUCCESS [ 0.110 s]
[INFO] jersey-connectors-grizzly .......................... SUCCESS [ 10.972 s]
[INFO] jersey-connectors-jdk .............................. SUCCESS [ 37.684 s]
[INFO] jersey-connectors-jetty ............................ SUCCESS [ 1.111 s]
[INFO] jersey-extensions .................................. SUCCESS [ 0.140 s]
[INFO] jersey-cdi-support ................................. SUCCESS [ 0.099 s]
[INFO] jersey-ext-cdi1x ................................... SUCCESS [ 2.327 s]
[INFO] jersey-glassfish-support ........................... SUCCESS [ 0.122 s]
[INFO] jersey-gf-ejb ...................................... SUCCESS [ 23.935 s]
[INFO] jersey-container-jetty-servlet ..................... SUCCESS [ 1.069 s]
[INFO] jersey-ext-bean-validation ......................... SUCCESS [ 1.287 s]
[INFO] jersey-ext-cdi1x-ban-custom-hk2-binding ............ SUCCESS [ 0.963 s]
[INFO] jersey-ext-cdi1x-servlet ........................... SUCCESS [ 0.327 s]
[INFO] jersey-ext-cdi1x-transaction ....................... SUCCESS [ 1.110 s]
[INFO] jersey-ext-cdi1x-validation ........................ SUCCESS [ 0.400 s]
[INFO] jersey-ext-weld2-se ................................ SUCCESS [ 1.625 s]
[INFO] jersey-ext-entity-filtering ........................ SUCCESS [ 1.494 s]
[INFO] jersey-ext-metainf-services ........................ SUCCESS [ 3.154 s]
[INFO] jersey-ext-mvc ..................................... SUCCESS [ 0.483 s]
[INFO] jersey-ext-mvc-bean-validation ..................... SUCCESS [ 0.304 s]
[INFO] jersey-ext-mvc-freemarker .......................... SUCCESS [ 0.556 s]
[INFO] jersey-ext-mvc-jsp ................................. SUCCESS [ 0.387 s]
[INFO] jersey-ext-mvc-mustache ............................ SUCCESS [ 0.425 s]
[INFO] jersey-ext-proxy-client ............................ SUCCESS [ 7.857 s]
[INFO] jersey-ext-rx ...................................... SUCCESS [ 0.089 s]
[INFO] jersey-ext-rx-client-guava ......................... SUCCESS [ 2.219 s]
[INFO] jersey-ext-rx-client-rxjava ........................ SUCCESS [ 2.397 s]
[INFO] jersey-ext-rx-client-rxjava2 ....................... SUCCESS [ 2.643 s]
[INFO] jersey-wadl-doclet ................................. SUCCESS [ 0.654 s]
[INFO] project ............................................ SUCCESS [ 0.085 s]
[INFO] jersey-mp-config ................................... SUCCESS [ 4.394 s]
[INFO] jersey-incubator ................................... SUCCESS [ 0.090 s]
[INFO] jersey-declarative-linking ......................... SUCCESS [ 2.363 s]
[INFO] jersey-ext-gae-integration ......................... SUCCESS [ 1.666 s]
[INFO] jersey-media-html-json ............................. SUCCESS [ 6.275 s]
[INFO] jersey-media-kryo .................................. SUCCESS [ 4.231 s]
[INFO] jersey-open-tracing ................................ SUCCESS [ 0.561 s]
[INFO] jersey-inject-cdi2-se .............................. SUCCESS [ 6.114 s]
[INFO] jersey-media-json-binding .......................... SUCCESS [ 1.395 s]
[INFO] jersey-media-json-jackson .......................... SUCCESS [ 4.235 s]
[INFO] jersey-media-json-jettison ......................... SUCCESS [ 0.757 s]
[INFO] jersey-media-json-processing ....................... SUCCESS [ 3.049 s]
[INFO] jersey-media-moxy .................................. SUCCESS [ 3.264 s]
[INFO] jersey-media-multipart ............................. SUCCESS [ 10.409 s]
[INFO] jersey-media-sse ................................... SUCCESS [ 25.342 s]
[INFO] jersey-security .................................... SUCCESS [ 0.143 s]
[INFO] oauth1-signature ................................... SUCCESS [ 1.697 s]
[INFO] jersey-security .................................... SUCCESS [ 0.420 s]
[INFO] oauth1-server ...................................... SUCCESS [ 3.225 s]
[INFO] oauth2-client ...................................... SUCCESS [ 0.302 s]
[INFO] jersey-test-framework-util ......................... SUCCESS [ 1.798 s]
[INFO] jersey-tests ....................................... SUCCESS [ 0.087 s]
[INFO] jersey-tests-e2e ................................... SUCCESS [07:34 min]
[INFO] jersey-tests-e2e-client ............................ SUCCESS [05:23 min]
[INFO] jersey-tests-e2e-core-common ....................... SUCCESS [ 2.941 s]
[INFO] jersey-tests-e2e-entity ............................ SUCCESS [05:04 min]
[INFO] jersey-tests-e2e-inject ............................ SUCCESS [ 0.100 s]
[INFO] jersey-tests-e2e-inject-cdi-se ..................... SUCCESS [ 7.884 s]
[INFO] e2e-inject-hk2 ..................................... SUCCESS [ 3.341 s]
[INFO] jersey-tests-e2e-server ............................ SUCCESS [09:15 min]
[INFO] jersey-tests-e2e-testng ............................ SUCCESS [ 14.975 s]
[INFO] jersey-tests-integration ........................... SUCCESS [ 0.084 s]
[INFO] jersey-asm-integration ............................. SUCCESS [ 0.876 s]
[INFO] cdi-integration-project ............................ SUCCESS [ 0.088 s]
[INFO] jersey-tests-cdi-beanvalidation-webapp ............. SUCCESS [ 13.917 s]
[INFO] jersey-tests-cdi-ejb-webapp ........................ SUCCESS [ 0.419 s]
[INFO] jersey-tests-cdi-iface-with-non-jaxrs-impl-test-webapp SUCCESS [ 0.355 s]
[INFO] cdi-manually-bound ................................. SUCCESS [ 3.960 s]
[INFO] jersey-tests-cdi-log-check ......................... SUCCESS [ 3.804 s]
[INFO] jersey-tests-integration-cdi-multimodule-lib ....... SUCCESS [ 0.154 s]
[INFO] jersey-tests-integration-cdi-multimodule-war ....... SUCCESS [ 0.372 s]
[INFO] jersey-tests-integration-cdi-multimodule-war2 ...... SUCCESS [ 0.375 s]
[INFO] jersey-tests-integration-cdi-multimodule-ear ....... SUCCESS [ 2.519 s]
[INFO] jersey-tests-integration-cdi-multimodule ........... SUCCESS [ 0.087 s]
[INFO] jersey-tests-cdi-multipart-webapp .................. SUCCESS [ 0.374 s]
[INFO] jersey-tests-cdi-webapp ............................ SUCCESS [ 13.563 s]
[INFO] jersey-tests-cdi-with-jersey-injection-custom-cfg-webapp SUCCESS [ 0.451 s]
[INFO] jersey-tests-cdi-with-jersey-injection-custom-hk2-banned-webapp SUCCESS [ 0.495 s]
[INFO] jersey-tests-cdi-with-jersey-injection-webapp ...... SUCCESS [ 0.460 s]
[INFO] client-connector-provider .......................... SUCCESS [ 2.678 s]
[INFO] jersey-tests-integration-ejb-multimodule-lib ....... SUCCESS [ 0.162 s]
[INFO] jersey-tests-integration-ejb-multimodule-war ....... SUCCESS [ 0.432 s]
[INFO] jersey-tests-integration-ejb-multimodule-ear ....... SUCCESS [ 0.373 s]
[INFO] jersey-tests-integration-ejb-multimodule ........... SUCCESS [ 0.081 s]
[INFO] jersey-tests-integration-ejb-multimodule-reload-lib SUCCESS [ 0.191 s]
[INFO] jersey-tests-integration-ejb-multimodule-reload-war1 SUCCESS [ 0.360 s]
[INFO] jersey-tests-integration-ejb-multimodule-reload-war2 SUCCESS [ 0.426 s]
[INFO] jersey-tests-integration-ejb-multimodule-reload-ear SUCCESS [ 0.474 s]
[INFO] jersey-tests-integration-ejb-multimodule-reload .... SUCCESS [ 0.080 s]
[INFO] jersey-tests-ejb-webapp ............................ SUCCESS [ 0.447 s]
[INFO] j-376-reproducer ................................... SUCCESS [ 4.608 s]
[INFO] jersey-tests-integration-j-441-war1 ................ SUCCESS [ 0.442 s]
[INFO] jersey-tests-integration-j-441-war2 ................ SUCCESS [ 0.367 s]
[INFO] jersey-tests-integration-j-441-ear ................. SUCCESS [ 0.486 s]
[INFO] jersey-tests-integration-j-441 ..................... SUCCESS [ 0.079 s]
[INFO] jersey-tests-integration-j-59-ejb-lib .............. SUCCESS [ 0.145 s]
[INFO] jersey-tests-integration-j-59-cdi-war .............. SUCCESS [ 0.403 s]
[INFO] jersey-tests-integration-j-59-ear .................. SUCCESS [ 0.366 s]
[INFO] jersey-tests-integration-j-59 ...................... SUCCESS [ 0.079 s]
[INFO] jersey-tests-integration-jersey-2136 ............... SUCCESS [ 2.354 s]
[INFO] jersey-tests-integration-jersey-2137 ............... SUCCESS [ 0.417 s]
[INFO] jersey-tests-integration-jersey-2154 ............... SUCCESS [ 0.350 s]
[INFO] jersey-tests-integration-jersey-2421 ............... SUCCESS [ 1.659 s]
[INFO] jersey-tests-integration-jersey-2776 ............... SUCCESS [ 5.978 s]
[INFO] jersey-tests-integration-jersey-3670 ............... SUCCESS [ 2.715 s]
[INFO] jersey-3992 ........................................ SUCCESS [ 3.938 s]
[INFO] jersey-tests-integration-jersey-4003 ............... SUCCESS [ 2.706 s]
[INFO] jersey-tests-integration-jersey-4099 ............... SUCCESS [ 4.083 s]
[INFO] jersey-4321 ........................................ SUCCESS [ 3.256 s]
[INFO] jersey-examples .................................... SUCCESS [ 0.084 s]
[INFO] jersey-examples-server-sent-events-jersey .......... SUCCESS [ 8.585 s]
[INFO] jersey-4507 ........................................ SUCCESS [ 5.107 s]
[INFO] jersey-4542 ........................................ SUCCESS [ 4.075 s]
[INFO] jersey-bundles ..................................... SUCCESS [ 0.118 s]
[INFO] jersey-bundles-jaxrs-ri ............................ SUCCESS [ 39.857 s]
[INFO] microprofile-integration-project ................... SUCCESS [ 0.087 s]
[INFO] microprofile-config-project ........................ SUCCESS [ 0.080 s]
[INFO] config-webapp ...................................... SUCCESS [ 0.705 s]
[INFO] helidon-config-webapp .............................. SUCCESS [ 4.363 s]
[INFO] reactive-streams-integration-project ............... SUCCESS [ 0.151 s]
[INFO] sse-reactive-streams-tck ........................... SUCCESS [ 17.353 s]
[INFO] jersey-tests-jmockit ............................... SUCCESS [ 4.772 s]
[INFO] jersey-test-framework-memleak-test-common .......... SUCCESS [ 0.265 s]
[INFO] jersey-tests-memleak ............................... SUCCESS [ 0.081 s]
[INFO] jersey-tests-memleak-redeployment .................. SUCCESS [ 0.146 s]
[INFO] jersey-tests-memleak-redeployment-leaking-test-app . SUCCESS [ 1.101 s]
[INFO] jersey-examples-webapp-parent-pom .................. SUCCESS [ 0.089 s]
[INFO] jersey-examples-helloworld-webapp .................. SUCCESS [ 3.595 s]
[INFO] jersey-test-framework-maven ........................ SUCCESS [ 0.079 s]
[INFO] jersey-test-framework-maven-container-runner-plugin SUCCESS [ 28.962 s]
[INFO] jersey-tests-memleak-redeployment-hello-world-app-ref SUCCESS [ 0.349 s]
[INFO] jersey-tests-memleak-redeployment-no-jersey-app .... SUCCESS [ 0.337 s]
[INFO] jersey-tests-memleak-redeployment-threadlocals-app . SUCCESS [ 0.300 s]
[INFO] jersey-tests-memleak-testcase ...................... SUCCESS [ 0.115 s]
[INFO] jersey-tests-memleak-testcase-bean-param-leak ...... SUCCESS [ 0.418 s]
[INFO] jersey-tests-memleak-testcase-shutdown-hook-leak ... SUCCESS [ 0.406 s]
[INFO] jersey-tests-memleak-testcase-shutdown-hook-leak-client SUCCESS [ 0.132 s]
[INFO] jersey-tests-memleak-testcase-leaking-test-app ..... SUCCESS [ 0.506 s]
[INFO] jersey-tests-osgi .................................. SUCCESS [ 0.076 s]
[INFO] jersey-tests-osgi-functional ....................... SUCCESS [01:54 min]
[INFO] jersey-tests-stress ................................ SUCCESS [ 8.969 s]
[INFO] jersey-tests-performance ........................... SUCCESS [ 0.083 s]
[INFO] performance-test-benchmarks ........................ SUCCESS [ 12.923 s]
[INFO] jersey-tests-performance-runners ................... SUCCESS [ 0.083 s]
[INFO] jersey-grizzly-runner .............................. SUCCESS [ 0.865 s]
[INFO] jersey-tests-performance-testcase .................. SUCCESS [ 0.105 s]
[INFO] jersey-tests-performance-assemblies ................ SUCCESS [ 0.166 s]
[INFO] jersey-tests-performance-filter-dynamic-test ....... SUCCESS [ 3.537 s]
[INFO] jersey-tests-performance-filter-global-test ........ SUCCESS [ 3.066 s]
[INFO] jersey-tests-performance-filter-name-test .......... SUCCESS [ 3.055 s]
[INFO] jersey-tests-performance-interceptor-dynamic-test .. SUCCESS [ 3.137 s]
[INFO] jersey-tests-performance-interceptor-global-test ... SUCCESS [ 3.159 s]
[INFO] jersey-tests-performance-interceptor-name-test ..... SUCCESS [ 3.000 s]
[INFO] jersey-tests-performance-custom-provider-test ...... SUCCESS [ 3.057 s]
[INFO] jersey-tests-performance-json-jackson-test ......... SUCCESS [ 0.493 s]
[INFO] jersey-tests-performance-json-moxy-test ............ SUCCESS [ 3.866 s]
[INFO] jersey-tests-performance-mbw-kryo-test ............. SUCCESS [ 3.324 s]
[INFO] jersey-tests-performance-text-plain-test ........... SUCCESS [ 3.130 s]
[INFO] jersey-tests-performance-xml-jaxb-test ............. SUCCESS [ 0.408 s]
[INFO] jersey-tests-performance-xml-moxy-test ............. SUCCESS [ 4.017 s]
[INFO] jersey-tests-performance-param-srl ................. SUCCESS [ 2.744 s]
[INFO] jersey-tests-performance-proxy-injection-test ...... SUCCESS [ 2.745 s]
[INFO] performance-test-tools ............................. SUCCESS [ 0.272 s]
[INFO] jersey-examples-assemblies ......................... SUCCESS [ 0.114 s]
[INFO] jersey-examples-bookstore-webapp ................... SUCCESS [ 0.544 s]
[INFO] jersey-examples-cdi-webapp ......................... SUCCESS [ 28.665 s]
[INFO] jersey-examples-clipboard .......................... SUCCESS [ 3.680 s]
[INFO] jersey-examples-clipboard-programmatic ............. SUCCESS [ 2.589 s]
[INFO] jersey-examples-declarative-linking ................ SUCCESS [ 3.172 s]
[INFO] jersey-examples-entity-filtering ................... SUCCESS [ 5.858 s]
[INFO] jersey-examples-entity-filtering-selectable ........ SUCCESS [ 4.543 s]
[INFO] jersey-examples-entity-filtering-security .......... SUCCESS [ 4.685 s]
[INFO] jersey-examples-exception-mapping .................. SUCCESS [ 4.094 s]
[INFO] jersey-examples-freemarker-webapp .................. SUCCESS [ 4.339 s]
[INFO] jersey-examples-groovy ............................. SUCCESS [ 20.590 s]
[INFO] jersey-examples-helloworld ......................... SUCCESS [ 4.933 s]
[INFO] jersey-examples-helloworld-benchmark ............... SUCCESS [ 4.559 s]
[INFO] jersey-examples-helloworld-cdi2-se ................. SUCCESS [ 5.055 s]
[INFO] jersey-examples-helloworld-netty ................... SUCCESS [ 5.809 s]
[INFO] jersey-examples-helloworld-programmatic ............ SUCCESS [ 2.815 s]
[INFO] jersey-examples-helloworld-pure-jax-rs ............. SUCCESS [ 2.969 s]
[INFO] jersey-examples-helloworld-weld .................... SUCCESS [ 9.042 s]
[INFO] jersey-examples-http-patch ......................... SUCCESS [ 4.249 s]
[INFO] jersey-examples-http-trace ......................... SUCCESS [ 3.620 s]
[INFO] jersey-examples-https-clientserver-grizzly ......... SUCCESS [ 4.286 s]
[INFO] jersey-examples-https-server-glassfish ............. SUCCESS [ 0.783 s]
[INFO] jersey-examples-java8-webapp ....................... SUCCESS [ 3.304 s]
[INFO] jersey-examples-jaxb ............................... SUCCESS [ 5.194 s]
[INFO] jersey-examples-jaxrs-types-injection .............. SUCCESS [ 3.487 s]
[INFO] jersey-examples-ejb ................................ SUCCESS [ 0.287 s]
[INFO] jersey-examples-json-binding-webapp ................ SUCCESS [ 0.692 s]
[INFO] jersey-examples-json-jackson ....................... SUCCESS [ 4.727 s]
[INFO] jersey-examples-json-jettison ...................... SUCCESS [ 4.848 s]
[INFO] jersey-examples-json-moxy .......................... SUCCESS [ 3.770 s]
[INFO] jersey-examples-json-processing-webapp ............. SUCCESS [ 4.097 s]
[INFO] jersey-examples-json-with-padding .................. SUCCESS [ 4.801 s]
[INFO] jersey-examples-managed-beans-webapp ............... SUCCESS [ 0.391 s]
[INFO] jersey-examples-managed-client ..................... SUCCESS [ 3.676 s]
[INFO] jersey-examples-managed-client-webapp .............. SUCCESS [ 3.921 s]
[INFO] jersey-examples-managed-client-simple-webapp ....... SUCCESS [ 3.005 s]
[INFO] jersey-examples-multipart-webapp ................... SUCCESS [ 4.584 s]
[INFO] jersey-examples-open-tracing ....................... SUCCESS [ 1.620 s]
[INFO] jersey-examples-rx-client-webapp ................... SUCCESS [ 25.134 s]
[INFO] jersey-examples-server-async ....................... SUCCESS [ 5.556 s]
[INFO] jersey-examples-server-async-managed ............... SUCCESS [ 4.993 s]
[INFO] jersey-examples-server-async-standalone ............ SUCCESS [ 0.104 s]
[INFO] jersey-examples-server-async-standalone-client ..... SUCCESS [ 0.805 s]
[INFO] jersey-examples-server-async-standalone-webapp ..... SUCCESS [ 0.232 s]
[INFO] jersey-examples-server-sent-events-jaxrs ........... SUCCESS [ 3.831 s]
[INFO] jersey-examples-servlet3-webapp .................... SUCCESS [ 2.819 s]
[INFO] jersey-examples-simple-console ..................... SUCCESS [ 4.348 s]
[INFO] jersey-examples-sse-item-store-jersey-webapp ....... SUCCESS [ 3.452 s]
[INFO] jersey-examples-sse-item-store-jaxrs-webapp ........ SUCCESS [ 16.567 s]
[INFO] jersey-examples-sse-twitter-aggregator ............. SUCCESS [ 0.402 s]
[INFO] jersey-examples-system-properties .................. SUCCESS [ 3.253 s]
[INFO] jersey-examples-moxy ............................... SUCCESS [ 3.554 s]
[INFO] jersey-test-framework-maven-custom-enforcer-rules .. SUCCESS [ 3.627 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46:50 min
[INFO] Finished at: 2021-08-09T05:44:10Z
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by seth-priya** [comment]
Looks like we have unwanted files in the commit @santosh653 , please verify and remove the extraneous stuff first

**Comment by seth-priya** [comment]
@santosh653 it looks to me as if your PR branch was not synced before raising this PR, you have to rebase it first

**Comment by seth-priya** [comment]
@santosh653 any update?

**Comment by santosh653** [comment]
@seth-priya I am not able to delete the unwanted files from the PR., I tried few steps but no luck.,

**Comment by santosh653** [comment]
CLosing this PR as not able to delete the unwanted files.

**Pull request closed without merging**
