### PR TITLE
Create javatuples.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Added support for ppc64le and verified the changes with build and test.

### CODE REVIEW

**Review by seth-priya — APPROVED** [review]

**Comment by seth-priya** [comment]
@nageshlop there seem to be merge conflicts for this one . please check

**Comment by nageshlop** [comment]
@seth-priya  resolved conflicts.

**Comment by seth-priya** [comment]
please squash the commits

**Comment by nageshlop** [comment]
@seth-priya squashed previous commits and ready for merge.

**Comment by seth-priya** [comment]
looks like there are conflicts

**Comment by nageshlop** [comment]
I will close this and create new PR.

**Pull request closed without merging**
