### PR TITLE
Create livecd-tools.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Create package travis file and added support for ppc64le.

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Is it possible to run "livecd-creator" or something as part of unit testing ?

**Comment by nageshlop** [comment]
@gururajrkatti I couldn't see any such tests as part of the package. Please let me know if you find any to verify the same.

**Comment by gururajrkatti** [comment]
Can you pl. check the README file

**Comment by nageshlop** [comment]
I check the README file. Couldn't find steps to create livecd. Please let me know your inputs and how to create the same.

**Comment by gururajrkatti** [comment]
Did you go through below section   --                                                                                                                                           

12.2 EXAMPLE: A BAREBONES LIVE CD

The command

# livecd-creator \
  --config=/usr/share/doc/livecd-tools/livecd-fedora-minimal.ks

will create a live CD that will boot to a login prompt. Note that in this
minimal example, since no configuration is done, the user will not be able to
login to the system as the root password is not set or cleared. `

**Comment by nageshlop** [comment]
Yes, had looked into it and also verified at local VM. There is dependency package dnf , python2-dnf which need to be installed to resolve the below mentioned issue, which I didn't find.
ubuntu@nagesh-at:/scratch/travis-job/livecd-tools$ sudo /usr/bin/livecd-creator --config=/usr/share/doc/livecd-tools/livecd-fedora-minimal.ks
Traceback (most recent call last):
  File "/usr/bin/livecd-creator", line 29, in <module>
    from dnf.exceptions import Error as DnfBaseError
ImportError: No module named dnf.exceptions
ubuntu@nagesh-at:/scratch/travis-job/livecd-tools$ sudo /usr/bin/livecd-creator
Traceback (most recent call last):
  File "/usr/bin/livecd-creator", line 29, in <module>
    from dnf.exceptions import Error as DnfBaseError
ImportError: No module named dnf.exceptions
ubuntu@nagesh-at:/scratch/travis-job/livecd-tools$

ubuntu@nagesh-at:~$ sudo apt-get install dnf
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dnf
ubuntu@nagesh-at:~$ sudo apt install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1.1).
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
ubuntu@nagesh-at:~$ sudo apt-get install  python2-dnf
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python2-dnf
ubuntu@nagesh-at:~$

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
