### PR TITLE
Create strimzi-kafka-oauth.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Added support for ppc64le for the existing travis.yml file in the repo. The build is successful for ppc64le architecture and one of the language is failing on amd64 which was seen in previous build too. Let me know whether the issue should be raised in community for amd64 build failure?

### CODE REVIEW

**Review by seth-priya — COMMENTED** [review]
@nageshlop looks like one of your travis amd64 builds is failing? https://travis-ci.com/github/nageshlop/strimzi-kafka-oauth/jobs/465902641

**Comment by nageshlop** [comment]
@seth-priya yes the build is failing for amd64 openjdk8, and it pass on ppc64le. Shall I create new issue for amd64 build errors at strimzi-kafka-oauth repo and merge this change?

**Comment by seth-priya** [comment]
Yes, let's create and issue and see what response we get. Let's keep this on hold for a while and re-visit again next week.

**Comment by gururajrkatti** [comment]
@nageshlop any updates on this ?

**Comment by nageshlop** [comment]
Have tried to build with latest source repo, still observing build failure for amd64. The issue is raised to community and will update once I receive further information on the same.

**Comment by nageshlop** [comment]
The new PR https://github.com/ppc64le/build-scripts/pull/620 added. Hence closing this.

**Pull request closed without merging**
