### PR TITLE
Build script for package go-msgpack

### PR DESCRIPTION
**Pull request by vikasgupta8**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Review by kandarpamalipeddi — CHANGES_REQUESTED** [review]
Please use exit code as non-zero incase of failure case.

**Comment by vikasgupta8** [comment]
Updated exit code from 0 to 1.

**Comment by seth-priya** [comment]
@nikhil-kalbande we can consider this for currency , https://github.com/hashicorp/go-msgpack/releases/tag/v2.1.1 is the latest release. A new PR can be raised and once done this can be closed

**Comment by nikhil-kalbande** [comment]
Considered for currency, team will work on raising new PR. Closing this

**Pull request closed without merging**
