### PR TITLE
grpc-core build script updates, dockerfile added

### PR DESCRIPTION
**Pull request by pratham-m**
Changes in JAVA_HOME export for rhel7.6 script and added scripts for ubi8 and ubi8-minimal.
The PR intends to resolve issue #836

### CODE REVIEW

**Comment by seth-priya** [comment]
looks fine to me , @afsanjar would you like to review as well? thanks

**Comment by afsanjar** [comment]
could we add a build Dockerfile as well?

**Comment by pratham-m** [comment]
@seth-priya thanks for the review

@afsanjar thanks for the inputs.
For the Dockerfile I need to check ways on how to dynamically set JAVA_HOME, instead of hard-coding the value. This may take some time. I will create a separate PR for the Dockerfile.

**Comment by afsanjar** [comment]
@pratham-m 
Regarding JAVA_HOME, you could add the below search to the build script:
export JAVA_HOME=`find /usr/lib/jvm/java-1.*.*-openjdk`

**Comment by pratham-m** [comment]
@seth-priya @afsanjar  added dockerfile & new build script

**Review by seth-priya — APPROVED** [review]
LGTM, please squash the commits

**Pull request merged**
