### PR TITLE
Create passport-local.travis.yml

### PR DESCRIPTION
**Pull request by genisysram**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
This doesn't have any ppc64le jobs !!! Also pl. take care indentation

**Comment by genisysram** [comment]
@gururajrkatti 
Modified the suggested changes

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Pl. update the travis build logs location. Pl. correct file location

**Comment by genisysram** [comment]
@gururajrkatti 
I have modified the file location

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Pull request merged**
