### PR TITLE
Add Power Support for Commons Pool

### PR DESCRIPTION
**Pull request by nagesh4193**

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Can you pl. add a comment in the travis file mentioning the reason for manually installing maven. Also is it required for both intel and ppc64le ?

**Comment by nagesh4193** [comment]
@gururajrkatti I have added a comment. The manual maven install code doesn't affect Intel, but still I have used if clause with ppc64le and committed the travis file. Thank you.

**Comment by gururajrkatti** [comment]
@nagesh4193 I don't see any  new commit with new modifications

**Comment by nagesh4193** [comment]
@gururajrkatti I have added the new changes now. Somehow previously my changes did not reflect. Can you please verify my changes now?

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Pull request merged**
