### PR TITLE
 adding build script for kryo

### PR DESCRIPTION
**Pull request by asellappen**

### CODE REVIEW

**Comment by asellappen** [comment]
[INFO]
[INFO] ----------------< com.esotericsoftware:kryo-benchmarks >----------------
[INFO] Building Kryo Benchmarks 5.0.5-SNAPSHOT                            [4/4]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ kryo-benchmarks ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:build-classpath (build-classpath) @ kryo-benchmarks ---
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kryo-benchmarks ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kryo-benchmarks ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ kryo-benchmarks ---
[INFO] No tests to run.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kryo Parent 5.0.5-SNAPSHOT:
[INFO]
[INFO] Kryo Parent ........................................ SUCCESS [  0.335 s]
[INFO] Kryo ............................................... SUCCESS [ 27.737 s]
[INFO] Kryo 5 ............................................. SUCCESS [ 16.519 s]
[INFO] Kryo Benchmarks .................................... SUCCESS [  0.687 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.445 s
[INFO] Finished at: 2021-04-06T13:29:20Z
[INFO] ------------------------------------------------------------------------

**Review by seth-priya — COMMENTED** [review]
I think we should accept the JDK version also as an argument and specify the versions with which the package has been tested in the script header rather that trying to test with both versions as requesters would generally use one of these

**Comment by seth-priya** [comment]
@gururajrkatti

**Comment by asellappen** [comment]
> I think we should accept the JDK version also as an argument and specify the versions with which the package has been tested in the script header rather that trying to test with both versions as requesters would generally use one of these

@seth-priya 
Added support for JDK version by passing an argument ,attached the test file (only content at the end of logs)

[test.txt](https://github.com/ppc64le/build-scripts/files/6286349/test.txt)

Pl check

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
