### PR TITLE
Added buildscript for marked-terminal

### PR DESCRIPTION
**Pull request by vathsalashetty25**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@vathsalashetty25 I see that there is one test failure in the travis job, can you please check?

**Comment by vathsalashetty25** [comment]
@seth-priya Inside container all tests are passing

added 130 packages from 70 contributors and audited 131 packages in 7.092s
found 18 vulnerabilities (1 moderate, 16 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> marked-terminal@4.1.0 test /marked-terminal
> FORCE_HYPERLINK=0 mocha tests/*.js --reporter spec



  e2
    ✓ should render a document full of different supported syntax (90ms)

  Options
    ✓ should not translate emojis
    ✓ should change tabs by space size
    ✓ should use default tabs if passing not supported string
    ✓ should change tabs by allowed characters
    ✓ should support mulitple tab characters
    ✓ should support overriding image handling

  Terminal escape
    ✓ should not be included in text length

  Renderer
    ✓ should render links
    ✓ should pass on options to table
    ✓ should not show link href twice if link and url is equal
    ✓ should render html as html
    ✓ should not escape entities
    ✓ should not translate emojis inside codespans
    ✓ should translate emojis
    ✓ should show default if not supported emojis
    ✓ should not escape entities
    ✓ should reflow paragraph and split words that are too long (one break)
    ✓ should reflow paragraph and split words that are too long (two breaks)
    ✓ should reflow paragraph
    ✓ should nuke section header
    ✓ should reflow and nuke section header
    ✓ should preserve line breaks (non gfm)
    ✓ should preserve line breaks (gfm)
    ✓ should render ordered and unordered list with same newlines
    ✓ should render nested lists
    ✓ should render task items


  27 passing (126ms)

------------------marked-terminal:install_&_test_both_success-------------------------

**Comment by vathsalashetty25** [comment]
@seth-priya I'll make Travis check and false and i'll add the logs in the script..is this fine?

**Comment by seth-priya** [comment]
not needed, I will review and merge if everything else is fine, as it stands.

**Review by seth-priya — APPROVED** [review]

**Pull request merged**
