### PR TITLE
Create strong-cluster-tls-store.travis.yml

### PR DESCRIPTION
**Pull request by genisysram**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
You don't need to add brackets to to "No" like <No> .. Any specific reason for choosing node 12 ?

**Comment by genisysram** [comment]
Modified with suggested changes , please approve the PR

**Review by gururajrkatti — COMMENTED** [review]
Pl. update the travis log location

**Comment by genisysram** [comment]
Changed the travis job link location

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
