### PR TITLE
Adding build script for monodb driver core (v4.1.2, 4.2.2)for ubuntu …

### PR DESCRIPTION
**Pull request by Manik-ibm**
…distro

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by sumitd2** [comment]
1. Failing tests are not listed at the end of the script.
2. Ensure script is tested for both 4.1.2 and 4.2.2, if not already

**Comment by Manik-ibm** [comment]
Tested with MongoDB version 4.2.6 
1.Build and test success
2.rechecked both version 4.1.2 and 4.2.2, build is success .

**Comment by sumitd2** [comment]
Failing tests are not listed at the end of the script.

**Comment by Manik-ibm** [comment]
Build and test success, no test case failure to list.

**Comment by sumitd2** [comment]
3 tests failing on a fresh container using the instructions on top of the script:

FAILURE: Executed 2394 tests in 12m 21s (1 failed, 145 skipped)
4527 tests completed, 3 failed, 145 skipped
> Task :driver-core:test FAILED
FAILURE: Build failed with an exception.

**Review by snehlatamohite — APPROVED** [review]

**Pull request merged**
