### PR TITLE
Create commons-validator.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Added support for ppc64le.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Pl. don't remove license messages/headers etc.. from original file. Also have you tested it with jdk15 ? In travis its using jdk11

**Comment by nageshlop** [comment]
@gururajrkatti comments incorporated, please review.

**Review by gururajrkatti — APPROVED** [review]
LGTM

**Comment by nageshlop** [comment]
@seth-priya ready to merge.

**Pull request merged**
