### PR TITLE
Create express.travis.yml

### PR DESCRIPTION
**Pull request by genisysram**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Whats the reason format used here is different than the original file in https://github.com/expressjs/express/blob/master/.travis.yml ?

**Comment by genisysram** [comment]
@gururajrkatti 
i have copied the worng travis , thanks for identifying the issue.
Please merge the PR

**Comment by Siddhesh-Ghadi** [comment]
Please remove the build-scripts from your PR @genisysram

**Comment by Siddhesh-Ghadi** [comment]
Squash your commits @genisysram. Rest all looks good.

**Comment by genisysram** [comment]
@Siddhesh-Ghadi , @gururajrkatti 
Squashed all the commits

**Pull request merged**
