### PR TITLE
Dockerfiles and build instructions for Eclipse-che workspace images

### PR DESCRIPTION
**Pull request by bivasda1**

### CODE REVIEW

**Comment by bivasda1** [comment]
Hi,

We will add license info for all contents and regarding "sed" command,it is
possible but there needs to be use multiple commands along with "sed" ,will
be complicated.
Please let me know if any other changes required.

Thanks and Regards
                                                                                                  
 BIVAS DAS                                                                                        
                                                                                                  
                                                                                                  
                                                                                                  
 Mobile: +91-9563329200                                                                           
 E-mail: bivasda1@in.ibm.com                                                                      
 Product Transformation Centre                                                                    
                                                                                                  
 INDIA SOFTWARE LABS, IBM HYBRID                                                                  
 CLOUD,                                                                                           
 Embassy Tech Zone,Colorado 4th                                                                   
 Floor,Pune                                                                                       
                                                                                                  
                                                                                                  
                                                                                                  





From:	ghatwala <notifications@github.com>
To:	ppc64le/build-scripts <build-scripts@noreply.github.com>
Cc:	bivasda1 <bivasda1@in.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	26-02-2020 20:11
Subject:	[EXTERNAL] Re: [ppc64le/build-scripts] Dockerfiles and build
            instructions for Eclipse-che workspace images (#145)



@ghatwala requested changes on this pull request.


@bivasda1 - 1) please add "apache" license file as done in other packages
in this repo
2) can we use "sed" command to just replace contents of this file - "
https://github.com/eclipse/che-devfile-registry/blob/7.3.2/arbitrary-users-patch/base_images
" with below , Any thoughts ?


che-python-3.7          registry.access.redhat.com/ubi8/python-36



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghatwala** [comment]
@bivasda1 - can you squash all commits as one here , don't want to put in 15 commits in main tree ? Ideally use git CLI to avoid having multiple commits.

**Comment by bivasda1** [comment]
yes,sure

**Comment by ghatwala** [comment]
@bivasda1 - please squash as a single commit  , rest all looks good .

**Comment by bivasda1** [comment]
Hi,
Can you please reject this pull request  #145 ,you have merged  #149.

Thanks and Regards,
                                                                                                  
 BIVAS DAS                                                                                        
                                                                                                  
                                                                                                  
                                                                                                  
 Mobile: +91-9563329200                                                                           
 E-mail: bivasda1@in.ibm.com                                                                      
 Product Transformation Centre                                                                    
                                                                                                  
 INDIA SOFTWARE LABS, IBM HYBRID                                                                  
 CLOUD,                                                                                           
 Embassy Tech Zone,Colorado 4th                                                                   
 Floor,Pune                                                                                       
                                                                                                  
                                                                                                  
                                                                                                  






From:	ghatwala <notifications@github.com>
To:	ppc64le/build-scripts <build-scripts@noreply.github.com>
Cc:	bivasda1 <bivasda1@in.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	02-03-2020 11:18
Subject:	[EXTERNAL] Re: [ppc64le/build-scripts] Dockerfiles and build
            instructions for Eclipse-che workspace images (#145)



@bivasda1 - please squash as a single commit , rest all looks good .


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
