### PR TITLE
Create sanitize-html.travis.yml

### PR DESCRIPTION
**Pull request by dthadi3**
Created sanitize-html.travis.yml and added Travis-CI support for ppc64le and amd64.

### CODE REVIEW

**Comment by gururajrkatti** [comment]
@nageshlop can you pl. review this

**Comment by nageshlop** [comment]
@dthadi3 Please verify whether the package supports lts/* release, If so you can add the same. Further details can be found at PR #537. Also this package has circleci in place.

**Comment by dthadi3** [comment]
@nageshlop Done with requested changes.

**Review by nageshlop — APPROVED** [review]
@gururajrkatti and @seth-priya LGTM, ready to merge.

**Pull request merged**
