### PR TITLE
Added build script for gnostic

### PR DESCRIPTION
**Pull request by atharv-phadnis**
Package Name: **gnostic**
Package Version: **v0.5.7**
Package URL: [gnostic](https://github.com/google/gnostic)

Tested on: **UBI 8.5**
Build Errors: **None**
Test Errors: **None**

Version Upgraded: **v0.4.1** -> **v0.5.7**

### CODE REVIEW

**Comment by seth-priya** [comment]
@Ryan-Dmello please review

**Review by Ryan-Dmello — APPROVED** [review]
Changes looks ok

**Review by Ryan-Dmello — COMMENTED** [review]
@atharv-phadnis any reason for not using latest GO compiler?

Other changes looks ok to me.

**Comment by atharv-phadnis** [comment]
@Ryan-Dmello No reason as such. Preferred the default available from the repos (**1.16.1**) as it must be the most stable. Beside the GO template too contains **1.16.1** so went with the same version.

**Pull request merged**
