### PR TITLE
Create travis file for eventing with power support

### PR DESCRIPTION
**Pull request by nagesh4193**

### CODE REVIEW

**Review by gururajrkatti — COMMENTED** [review]
Can we not run End-to-end tests (e2e) ? Rest all LGTM

**Comment by nagesh4193** [comment]
@gururajrkatti  I have added a script for test and updated the travis file. Please review

**Review by gururajrkatti — COMMENTED** [review]
Pl. refer to https://github.com/knative/eventing/blob/main/test/README.md and check if you are able to run e2e tests

**Comment by nagesh4193** [comment]
@gururajrkatti I have updated the script with tag e2e. The tests are passing only for go test unit tests, but for running other tests, it is not working as the prerequisites does not yet support private registries. Can you please review it?

**Comment by nagesh4193** [comment]
Guru, As discussed, this is the link https://github.com/knative/eventing/issues/1862 where it gives the limitations from the community.

**Review by gururajrkatti — APPROVED** [review]
ok

**Pull request merged**
