### PR TITLE
Create flask.travis.yml

### PR DESCRIPTION
**Pull request by nageshlop**
Created package travis file and added support for ppc64le.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
I don't see tests are being run here. Did you try running the tests through tox ?

**Comment by nageshlop** [comment]
@gururajrkatti yes looks like [python setup.py test] command didn't run any tests. Will check with tox and update.

**Comment by nageshlop** [comment]
@gururajrkatti With tox the tests are failing, build is going fine.
https://travis-ci.com/github/nageshlop/flask/jobs/484450949

**Comment by nageshlop** [comment]
Had discussed and closing this PR as tests are failing with tox.

**Pull request closed without merging**
