### PR TITLE
build script for pact-go v1.0.4

### PR DESCRIPTION
**Pull request by vaibhav-bhadade**
## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

### CODE REVIEW

**Comment by seth-priya** [comment]
@Sapana-Khemkar please review

**Review by Sapana-Khemkar — COMMENTED** [review]
build script file name must be in lower case. Refer `[this](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)`

The name of the script should be <package_name><distro_name><distro_version>.sh where package name is the name of the github repo and distro version has to include both major and minor versions (example 8.4 as opposed to 8)

**Comment by seth-priya** [comment]
@vaibhav-bhadade any update?

**Comment by seth-priya** [comment]
@nikhil-kalbande  this looks like a good candidate for currency, lets close this PR once we have a new one created

**Comment by nikhil-kalbande** [comment]
Considered for currency, team will work on raising new PR. Closing this

**Pull request closed without merging**
