### PR TITLE
Added bluebird.travis.yml

### PR DESCRIPTION
**Pull request by sanjaymsh**
Hi,

I have added bluebird.travis.yml in this branch. For travis build log, please check here https://travis-ci.com/github/sanjaymsh/bluebird/builds/213266891. Please review and merge.

Regards,
Sanjay

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Any specific reason for adding arch: amd64 for node 6, node 7 etc.. ?  Also these versions not considered for ppc64le. Is that intentional ?

**Comment by sanjaymsh** [comment]
Hi @gururajrkatti The reason behind all those changes are here https://travis-ci.com/github/sanjaymsh/bluebird/builds/213264165. The earlier versions of node before 6, is not maintained and its throwing error in travis. So i excluded and added in allowed-failures section. node 6 and node 7 is passing on amd64 but not passing on ppc64. so i did not added, i debuged and concluded that it wont build successfully here. so i did not added for ppc64.
Please let me kn ow if there is any other changes required.
Thanks !!

**Comment by gururajrkatti** [comment]
@sanjaymsh if the issue is only on ppc64le and still failing with travis_retry, pl. check and update the comments section in travis file on the details such as any dependency not supported etc..

**Comment by sanjaymsh** [comment]
Raised an issue on community tree https://github.com/petkaantonov/bluebird/issues/1673

**Comment by gururajrkatti** [comment]
@sanjaymsh community issue closed saying its problem with eol older versions of nodejs. If it is failing only for newer versions of ppc64le pl. check and update the comments section in travis file on the details such as any dependency not supported etc..

**Comment by sanjaymsh** [comment]
Hi @gururajrkatti , For nodejs-6 & 7, ppc64le builds are failing. Reason behind the failure is just one test scenario is failing with below error" √√√√√√√√√√√√√√√√√√√√√√√√× FAILURE√√√√√√√√√√√√√√√√Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Unhandled rejection (<[function succeed]>, no stack trace)
Some tests failed: 
    async.js For additional details you can run it individually  with the command `node tools/test --run=async.js`"  

Detailed log can be tracked here : https://travis-ci.com/github/sanjaymsh/bluebird/jobs/481800678. 

And same is the case with nodejs-7, and thats why i have excluded nodejs 6&7 for ppc64. Now everything looks fine for me. Please let me know if there is any other changes required.

Thanks !!

**Comment by gururajrkatti** [comment]
Pl. update the comments section in travis file with the reason for excluding. Did you explore "travis_retry" and/or any other debugging env variables ?

**Comment by sanjaymsh** [comment]
Hi @gururajrkatti  Yes , i have tried it, It is not working. As per suggetion in log, i tried to execute the command to test that scenario. Then that one test is only getting passed , and rest of the tests are getting omitted. And same is happening on my VM as well.
I will update the comment section of travis file.

Thanks !!

**Comment by gururajrkatti** [comment]
@sanjaymsh any updates

**Pull request closed without merging**
