### PR TITLE
Added Build Script for Kubebench

### PR DESCRIPTION
**Pull request by ujjwalsh**
Hi,

I have added travis.yml file for httlib2 repo. Please check.
Thanks ,
Ujjwal

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
There are some jobs in the jobs include section such as py3-pep8, py3-package etc.. are they not needed for ppc64le ?

**Comment by ujjwalsh** [comment]
Hi Guru,
Those jobs were not building in leppc64 architecture with the matrix jobs layout , so submitted with the raw format.
To build those job either i can skip the matrix layout and  cascade  in the normal sequence, but it can alter the repo significance for matrix job layout . Please suggest me some method.
Regards,
Ujjwal

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
1. You can use matrix for all the jobs
2. Pl. do not club multiple files into single PR. As mentioned earlier this will make the tracking difficult
3. In the second file, whats the reason for removing clang for both amd and ppc ?

**Comment by ujjwalsh** [comment]
> 1. You can use matrix for all the jobs
> 2. Pl. do not club multiple files into single PR. As mentioned earlier this will make the tracking difficult
> 3. In the second file, whats the reason for removing clang for both amd and ppc ?

Hi @gururajrkatti ,
For the "vsearch" repo one of the Clang component Support is not there("AltiVec support not enabled") , due to that i have commented out the Clang.   
Please let me know how can i proceed with or without clang.

Regards

**Comment by gururajrkatti** [comment]
Is it not supported on amd64 also ? Which version of clang did you use ?

**Comment by gururajrkatti** [comment]
@ujjwalsh , any updates on this ?

**Comment by ujjwalsh** [comment]
> @ujjwalsh , any updates on this ?

Hi @gururajrkatti ,
For the Vsearch Repo:
I have tried using the focal dist still its not working.
https://travis-ci.com/github/ujjwalsh/vsearch
(Altetiv support is not there for leppc)
I checked the packages @ (https://power-developer.mybluemix.net/packages/) the other packages are available update which we are using in build 
In the case of Httplib2 python2.7 cases are not executing .I have updated the matrix job format with both amd and ppc
https://travis-ci.com/github/ujjwalsh/httplib2/builds/217588538

**Comment by gururajrkatti** [comment]
Is it not supported on amd64 also ? Which version of clang did you use ? Httplib2 - you need to update the file here along with new travis job location and submit after squashing the commits. I see the given location has a failure. You also need to update for that.

**Comment by ujjwalsh** [comment]
@gururajrkatti  Hi Guru I have Added Build script of Kube-bench repo in the preexisting PR please Check it and let me know if any modification is required.

**Comment by gururajrkatti** [comment]
What is the reason this is included in the existing PR ? I suggest you create a separate/fresh PR for kube

**Comment by gururajrkatti** [comment]
>>>What is the reason this is included in the existing PR ? I suggest you create a separate/fresh PR for kube
@ujjwalsh whats the update on this ?

**Comment by seth-priya** [comment]
Closing as there is no response on this

**Pull request closed without merging**
