### PR TITLE
PR_AddingPowerSupport_body-parser

### PR DESCRIPTION
**Pull request by santosh653**
creating body-parser.travis.yml with proposed changes.

### CODE REVIEW

**Review by gururajrkatti — CHANGES_REQUESTED** [review]
Isn't node 4 and node 9 supported in ppc64le ? What is the reason they are excluded ? There are lot of blank lines after the exclude, you may want to remove them

**Comment by santosh653** [comment]
there were failures for 4.9 & 9.11 of Node_js versions on power, moreover the code is running fine on the latest Node_js versions so I have excluded those.

**Comment by santosh653** [comment]
Eliminated the blank lines in the code.

**Comment by santosh653** [comment]
@gururajrkatti @seth-priya Can you please review this one?

**Review by gururajrkatti — APPROVED** [review]
LGTM. It would have been good if the failures of node4 and node9 were looked into

**Pull request merged**
